apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:3iKrzabC9BzeCAgq/UIKPeekGFcdssoicDKT+dgUmDe5aqINNrYf/tURKtetyAXMivxuqH70xOx6nCW6IeZL2oXvV1WVbRPMVdatNZaJ2CwdD5cAgZ0ymiCUCoXqka6MCO8RQjpPK+ypItFz0TNuX90ViEVwFgFg5t4tHWMeMjyixhGbCJ90o5+VcFyHHuXXGYmHLl03JMM1c3QT6x4ZHygTREezhl6EHPor6RDg3aRRZkBTTc3Wa3HOC20kIpT4nslJ4KgiUyq51ZduDbcp4GwmNig+VbjRJ9vekJipTIV3YqPx68WGvnOWsZw=,iv:ljfwl5193V49cftn/ZCdrsh+tI7tmS6OBkXux6UgxOk=,tag:Q/8R8W/qU0NsSzK3ozr4PA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR1BFbGFTbkp6STU1SjlT
            WlNWc0pGdTdTaFk2dExKQU9abDhVWGpEQ2tJClM4bDc0bVVJZEQ1UzZRSVgycGMz
            SnFOUVZDd041Z1FSbDdNMnRQTUgwdWMKLS0tIEdVOGthLzNMMWtjelV3bC9RTld3
            OXpXZVFIdXRsTnhrbzlTTTg0NDNzemsKHCCO4Gwl6tKTKtNDVov/8ISOeLe/esBS
            pSQzDVH1E90YuztS6n+boLPRFCOGWoEbL//UeULytqpPm0eWBFoSWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T05:59:12Z"
    mac: ENC[AES256_GCM,data:heMRHsKr/0NMQN81s56i4qLJJ+YKMNpEfKEgN4QYKSw83K2M3sUI9wfOGN0l7s+WnPelXxVOpGp8oJfFfKC5NyaKBlc++Uk13EWilwPNMaTd6E11AfxUVTqOpFPvoUreT0V96VXQZiwl26t3/0MJAWrfUce997g33ZMARCXUh5g=,iv:ykbHw/7hKhzNTPe67WNyjq0KcNbG+IfqeG+uinjkuqk=,tag:2H0iWJ+qu57Zrs+4UeLG3g==,type:str]
    version: 3.13.1
