apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yvY0zRUpZIVAClCSxVQ26CUh0Lg8Ix36PY/9iiEISttE5CLQYGIayE4ckZ/8LtYlU7/7VA7zg7j/GsnCyRBwZQhkJOZR1x3+Q9gvd8iCejB59HQ1sAOCHOA3Jtlw4YeBp2pxMDaI289eOM0mDJRbv6l7J5MwoXKN3xxQUbnfAtL4AnqPpK7YgjIemxEpSufcKSr9e2SSC5+zzvrCNMB0+w9KrjB2trwcShlyVvP3/4kTNWJBd5srwnzx2SibaKR6q0qQnGfZ2A6v3lgcPj0N1zTXv0q9W9lw2DXgn8Fo/iYgHL8GmG91cCPTQCg=,iv:sFcCX1B6nvc0xQkYAr5BbgBBlocOtqOUWR1E+Z3+btk=,tag:YvYq/o7jsxoCi8/cUUpURQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFlMelNmaUxX
            Z01KQjJYR1prY1h1Qk83bG1SYllNYlcvMTVVWTJZQ3dHZGRWTVdIOXBqaXZIejdU
            MGJRVjRRWTBsdWV5a1F0ODJlRXNXMzFGRkhYd201L2U4cGZVbWw3bHdlWHpHN2Jy
            bG9pVytwNFNJZnIzZ0ZBem5jM0w5T0lBOE1mUkNNemZpdHRqVkVkOWZqcm1qMkxS
            RWlxdnozN2xpcHhWb1VLR25aVTcvNHcrRU5kZ1VleHhCV1BpTFQwUVpKNDUzbGNy
            U3owTXZqajgweDVWak1iQ1J6K3R1TlVRK3BBa2h3Mm1kVlpGZU9DUkpsb3JJU0p2
            V3VjR2l5STBzYkpybjZtT0tZOWFCakFHbnNEQXR4TTQ5NWNUMUpBeDA2d1BZOEkw
            YXhxY1hjTUdtcy8yNGFYaitVbDc0TUtsaU5MMlpBUm9abFZoTHlxcm5JQ3BPVmhy
            T0lpT0RLZllyUEZtWlk2WHlUL2RXU2Q0VHpKSWQ0T0JUUkRlS0sxcEpTRW8xdWdV
            c1ZBejZoSFFFYlhHYzlMbGkxRzJRUnpDYVFha0YrdXdpd2NyaXJXai9IOXprYzJ3
            UlRvb3dwaWY0YlR2YWQ2R1RuWmZVN1cwbkhST04ybWVUNE5lR3RIcmNyai9sdHp6
            Z2ZqM2VOQWJWWWJsNjI1YjBQSEs4NUM0UzNJeWo3SmtROUxrMFlHdit1KzlOY20z
            eHA2Vk9lRmRiVCt1NkdxaDZrWjRnWENrYUU5Q050bndBMjVZbFFBK0hGOFV6bGRT
            Z3Q1b2pzUGZLb2hDdjJRQ1B4OWo1c0dMTCtva0JTZnhTZjc2cmZGVzBnVW4zWFRo
            S2xXRHphV0NnV3VxRVV4S01rV3NaZWF1VFkwcEcwa01hZFFQMS94NnJkdzdseDdm
            ZkVLRmpaOEorWmRJVDlIZ1h0TFFadUJ3dGVVMnl2M0theDY0WmZURHJWV0VyZlFu
            U2Q0THZBMHQ0NUtxQWxEdVBMTTZseFR3WTBXUVRmeGRhMU1KRWcrSDZQaXhxbkMy
            cjlUNGI5TmxIOTNTMVpmclE5N3BSWkxJVDMvM0dYZUZKR1IvdStEeUdtd0pNTmVK
            UnJKQWMwTEUrMkpTc3AzN0xVeU1tblIvak9YZXNSb2tyNHc3dTZhdStxb0VwaC9E
            TDErajJOdHd0YnV3dEMvVUVmaEFmS2FFUFc5NDIxRzNJdnBwbWptL3VFU2F2YlFO
            NitROFBwTE8rbStreEc0MTE5bStvOXFURlhtVWU0SDMzM3VDeVYrV0xwTkxnbkVw
            VUlBTCtNbkVDT09TaXl5ZzBFV0RDS2JHNGZYcFNpRkpwSjlXc0RDVkFHQ2xBdy9F
            RFRwZ2lSajlTVFVMRmFzRjN1L3dxVldIWFhKeVRsTmQ3R0NKTXNEMVdldFpxVmlW
            Nzh1R3dVM2FGTzFRME1TM2FzaHl6eGVEeTBKbzdWRVlRNTVEc0swcXhmdi9LNVov
            M0VuR0RyQU9ZWG9HTkNsQjMwdDIzaE9ydGNYV2c2UUJwcUkrRW9DWjQ1bS9ITklS
            cEtmZlFkQjNxOUpzbTdTdDZyczRDcml1TmEyOU5jMi80OGRBQ1cwZDB5L0dUUkVZ
            Tm5WNzJaVW1RNHVHMTlLYVNrb2ttazMzNld6TEhVbk4rYm9sckR2b3lZeEdka1E5
            d0xXV1dqTC9hTEJ1QUZTdXh4a1JwYlJyZXpIQ05zWVlPWFNNcGNXYVlwNlgwMmtW
            T0xjNUdjRDNSVEY1Z3BsbjkveS9TcW5ObStzc1k2NDBodE5VczRST0dkV1RCT3cw
            V25BaUM1VVZzSkZzbXdXVUhlb2JPblN2Q25LdE1xRU1IT0hmNFkrbkRFRmYxTm82
            TUxYRkY3UmQzaUtvcmtOdnJxS1lFT0hHOHFWNGJDNnR0ZVMwQzZkN1ptSlM3VGVp
            cjBoTTBXSjczc1gwSGl4SDFxdW13cmloOFVGUGhVVVRCaWt6VjBKZzVmelliQQpB
            WjB0djE5c2lhVVQzaENjT1h3Y0NUZGV0eEw2ZjVCL1R0TFNhbnB4Tko0Ci0tLSBC
            Z3IxSlNPbHl1NkM0RGZKR1hmckFUeld1ZURmRDVoYzU2MWRMQXRuclN3CrqafZjb
            xrkZ5oVfTOVkd5trqQ6ZEC8Iil20fBxx9fEeHqaF76zxzUyz4FhashAn/D7UkwKD
            ImXi4qBfbQCKZPg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:19:54Z"
    mac: ENC[AES256_GCM,data:Fe0XIlxppqv40wOgz6rRaBmTY32+j/goqau8fPIpfIFWWYr0XiSooPCLtv0HL5lkZdRGXYsP21Cb/gpzW1IOGfzs3b2gG+WJ2H4edW7Aey4NNFKNvxl2yO6EcVtWRxmskNwzOSI0bdguFW+VuYFZTriVwmzTWtLRkTo6Mpl7V84=,iv:dTQY+ljHSWtY3howAUe0106vWr0/SX8upVwGaCyu3Nk=,tag:Vveu0CCZlNlpYOvABqc94A==,type:str]
    version: 3.13.2
