apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:cszc7fVuHtTzlFq1,iv:NEYMlO14HkPUflGDY7eLNUcUTAqNj7m60vUa+dsTxGs=,tag:VMqM5GOeFpTRs/nfw2et5g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:cvU/ah6pJq5J1vL2hY7pmOyaQ8R+nq/Y+lmVf5XQfwI=,iv:H5s8nb4IMfM+nTrvcBL+j4TH0CdbVPy3rxykfW3Pgwg=,tag:oOcadyUQSYU9CEl8YeFo5w==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHQ3TFB5TUY1
            SHM1K3VCSndsZXRiOW5KSERra1U3UlZPZ0U2RWdsTE9kTjY4WWVuZExwRGc5SkNi
            cVNrVlZSelFWNnVaNVV3cytneGloZGVqbStvTGtrZ2dSR1EvaHZ5ZWVLekVHT1ZO
            NEsvTmZCa3hWYjB5Rld6Nk9way9NazZBaEl1azdmeVVHOTlqZUhhSWtieE1XYVIz
            anJha2ljNnZ2RzlUYUFYMkVSR21WQmhBU3g4dGRFVmtRMVlDY1FleTlpSDlpSlNS
            UkJCTHNHRHVXeWc4aW96cnpWUGdIdDE2MXRpcUVCaVhZVlhaMGpKam43NHAyY2xZ
            anlkdXlodW8vSW0wRlZjeEs3dEYvbjBUNEc4ejFneEROWmorbWNBZ2YweUhnRGtL
            bzVRZ1Y1Y0dYTldpSTJjZGpNejNqS0NYQyt5VTNXWWU0RVhqNjAxanh0czd5TW5V
            R1ErZVhSTmRNRitVd2pYbXIxWnJXd0JhRVV5bVB3UTVYM0owdHpiSVkwNG1yQVFu
            Skc3QWx1WUlHYnJnVElDd1pRMFNjb1krVGVCRDlDRmhudlM0RGxvSWFsNG04MjRU
            V0FISEgvaXd2dVBMak1YYXJ5Q0FVd0syUmltT3htbUptbDdjRFo0SVVoeHJ1QTdN
            cXVMNm45SWZURmdLOXR5VlFmRXh3RnNDaW1iR2JNNFdnQmNtYzdkNXR0WXZlRGlF
            ai8vWkNCb1BXMjV0U2t4cXhqUWI4cEg4NFBsUkdMNmVpbTByTFA5SEJvTHlSRHBa
            Q2J2Wm9qSUx3T24yRGpiUjFpMjFYVnd2R1BXSEZ2czZJU280YzJKMzJNRUtQb1A1
            MGNERE9PZkVVNDNUb1JybjI2Y1RIVVAyY2hETSs2QzFBT2ovWUtDQ0VqZ2ZkU250
            d1BzUlZ3YlBhdEhmcGhxb2lQcEZ6TlZId0s3cWU0NnlCbk94L1JDZWJsWnkxNzQ4
            VGFhaUN0R2t0VVJPZ0NLWVhUTW00WjJneE0rVnZQTEZsRmFOZXZCS3BaOXZDODdO
            ajd2TkR1MmRCOU5yZDdwMWt2TXMwWkFleTRhUmYxWTFsUlZkVGxkelI3K3FzUmFE
            bXhMS29PZEN4ZFlBa1lTbTZHdDA3ZlN3MURZNlY0QVBjT2JUaEN6U3hZMlNYdmF1
            OEI5RnFWZ092MktnS1dKdU4xM1JyMjNSZ1NRTkhLWi95OGtHRTg5VTNXbWswa0pt
            RDA2OHY0SithNm5zNXo3SW01QytTVTU5WWtLQ3dkOVN3K1d2Y01OSVcwcThmSXhL
            UERlUS9QbWtwZTBRSXFTVGw0U3VnR3Y3V3kwYmdrTng3REhzT3Jqb2EwT2hJL2ZS
            SDAzY3FCc29Tb1ZVclZVRWEwaWdCeUluNkplNkpQcGFrQXJtY2M4cUNHVVZDMEk4
            THdEYlh4QjVpMlMrZnFITHAzT3UwdWt2VFNNR0duallQWjYvYVhuUW1rTTVTaVRw
            d0RFYTVGR1BoVlVVMVZKU2J2OE5lalVrU2E1MkVyVlc1NEMzTlBvYXJEVUJlQmRy
            RE1odjJSTkZ0bDRwbE9rem91bTFIdmRVK29DYVlYOTdHZDFzbEZZZzRZK050b1N1
            VGFLTEEwcXpna3NoMUJPcGNEakJaL244ZFd1WDllMnBCYkYzZzIzR0RPSE9HM2Jh
            bFZ3aVYwTE9RRmtIVTlnTEFMd05xQ09SZkoyaytQZkN3UTVvL0N3aGxLRXhGVlBp
            R0JhT2plMFFYNGp3VEJzRmZUSVpyd0VkaWUxY1FVdmhNdmNNODlkYmZXU0RkTlZu
            NzBkWlc5ODVBNHZnU1JzcThFZElpSXN0TlkrNUF0T0J1dmVmVXRKY2NKUkFEbWtU
            ckp0SG1PeVIzeEJuOGlHaDBqd0pvT2lNTXFPRkJGZ2F2UmwvaHBRNzNpT0pkSExk
            TDFIL0hqb2IvSDh0YnB2anR6aitLOVZJdGhrWjlrTmRQS045dzVWdDNUNjFZZwp4
            YmNlYmZLRzRDUk1ST1BmQW9sT0wwSHM3aXF5TjFubHU0OTJ0T1RyQWlnCi0tLSB2
            b0JHTldWTkdDck1nQXJhMi8zbVpEOHlhbFA5T3U0bXorRmdLQnZacUtNCtfRsJvp
            ugsUbY7uaUuPegaAmCfyfRoQ4wYPfPYbPWYnS2MXDajbjgVVbS8VMGGhvXbzyubW
            xYT2jGnpbR0A5zA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:19:59Z"
    mac: ENC[AES256_GCM,data:F0gLh4FL17tbUaBbynlaFJsgC8CIynx1lLctInYZsiVuuWdj4zwWj33hHtXnUYsqSuUiMWO9C+Ly5xYb7OS5uYVJf0V/pJOKGYzN/baVb667DZyiTeVoYEXlYO9h9BhB/NIipDzEirXchosl90ORk/8bLKURk3LDeROOTdkcVEo=,iv:G+j4xRXiDgQ4NHwPfD+DWGEKrByE53oDUWR+7v7QVxo=,tag:F2RZrkaVvROvyIdxFnK1cw==,type:str]
    version: 3.13.2
