apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: homarr
    namespace: homarr
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: Create
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    persistence:
      homarrDatabase:
        enabled: true
        # name: homarr-database-longhorn-pvc
        storageClassName: "longhorn"
        size: "2Gi"
    replicaCount: 1
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
