apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:fdAdLkI+I3LigclwxLW0mvvRw1FH8Xn3CeE7eBU6YY6MpOgOyajPeUWnKU1UOwywZBPWIjYn4rAU9z/TqHGAal+SsIKv+Nmd0kDfR/mkHFd5apQz0fQlLM2Sr80XnQmAVX27HXPztrC7vqvRq/Ap1LOGNffNXq6JDCTaxlQnl65/N+6TwpolZQrsj8mzKGn+o9vRQtSEjPup4E7NHVaPlEtxSuhrwlkE/5k4MjxiE0uJPZH1DUt7Oxy8yv3aErddFmCHpqpOsC2/y1FszSx5vN8ZKhsmCrbUBtsk4ciz5ec3dEVURKRMTnWOuao=,iv:vXmxoK/C7HIyuijoh2lqdoK7hNpag9uxFB80JN49xNk=,tag:SOG2rJnNIzhMKSJdx13pBw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDA2b2FNMk4v
            NERSNldFVFBjdVYxcCtkTGFRQjVsT0F6cmxqaTljNXErbGRQMHN3VGliSDVLRkVr
            cTRNcnVBWEJCU2d5ZTlPVmwzc2l1NUJaNHVoUmtCYUN1Sy9GNW1SL1VGeEtkbzlG
            bGRzazU2UkxXQnV2S0N5R2pjMWFpUW9LL3R0Y014bVFUYmtNcExzdytkNUpwdERK
            RGlsZGVycndzbWZnSDJJVTVHbStNK1Y0U0ZPb1BrZ09QTmQ0akdidEI4WXJsSVdH
            dGZVVVJqM2hIbVpJRWNjWGNob0l0dXNVVTFnVjk2SU9hRHJmclVlOW9NckNnUklr
            bTI0WnpNZmF3VFgyYWt0VW5BczF2WHV6S2RXM1FhUjYvTlNBOUFOSTR4MVhRbHBB
            UGpRQnd2NE9Td1Z4QXViMThwSXhzWm53KzBuOW1PMlIzcW1GVUIyNWFTaVdSeHh6
            dmVBcThHTnBxQjN2Q0lWbktjbU0xSm5tSVNiNFpZQ3d4aGxDckNKN2I1Uy9oSjdN
            Z2s4OVJKeWdnbW94N3cvSUlqdzFKdWNVdlYzZjVnYnlxVUpXTlRpRjhFWFlwejYv
            TVc3RzJaem8yL1NZR3ROS0xRM3pwU0R3RUtjNWFWc1I5SkFrL2krVnBQYjRUSldG
            Y0hDNk9pRmVhcEFPVXN3MUhISWsxWUdtRnh2MHJubDk2OFhxTElkODdYT0NOVVhO
            WDR1OVBsdWY0Sm9odGtJVVJwQTk5eGhsMXd0WUJCZnkyczUrQk85Y1RjVjRPdDJx
            eWZZbEpMS1JwbFlxWnNYR2ZFTGpZS0lsQXRnd0FVRWpPWWpRVktaWDVYUkNPSzVh
            NVBndzNPL0xkNFN2d2hhZGxiN3BoeU9JaEdTYWRCOExYVXNnYUNEdEpnQ0tGM3RI
            YjVmZjhzQTlYNE1HY25TdjJWSWlha3M2Z2lNMHp0bUdGUjlkamVCU2ZoUWY4U3NK
            c3g3UFFJeS9RYk4wNnNvTndWYWk4MHZWK2ppSXFSenFud0ZIMmNkV3Ywb25XRko0
            RDcxMTFRWmdOZGM3cG9rNXlLeWtjZFdnYlNuNUZHaDA5NWVUcWY2SzE2R2F5eFFE
            YldDUTBRS3U2YzAvWm5YWmFTTVRsSXJZUmxqNlN6NUlSdHBqbHBKYk5zek4rUHBr
            bnFHb0grMnViZ0dIMzFXMmUwTUZTVEJrTWNlR2ROQ1JLRDhMajRxSHhMZlg2S2Jo
            M1UrV01sS1UvbDlqUmsxWi9oNDc5S2MycGw5NFJoQjJsb2FtQlJHN0FUZXZoSmM3
            bjBXOEJVMUVTdHU1Z1FIbEdOVU5yWmUzWEdtYURUbUdGOUV3amh5NnFlVFY1NFRO
            QW90Z0dpQkZwRnRkVXJveWJsN1dKYUxzVU9zdGJ2MG9OY3FyVHFmS0NwWG9NaEdO
            eURLTkxxc1p6OVUvUGdTdGtIMGk3TUlobVBXNjhzRVFtTCtUWnJJb0xmWjRadWw5
            MFlSVUNpR2I1bGR3OUZJYkJ1bjIrOElyZitJSm41ekxEUmVGMUUrZWlLa0tMMkp4
            b3Q5QjlPK0Uvb0V0WDJ6cFZpV2xFMWRKQ2YzeHlBcDdQR0EwcmdWVDByTXd3cVJK
            NUtRTEp0a2wxc3dzNWswMGVHR2lYaHV2TUxhLzdPWnFEdG0vaVMySWVlVDZVUE1G
            N1NZQjcrRHV1Qm83bHpUbHVPaEtUSTBERTBPcjRhdVNyaFJKeVJLd1k4VHFySGtx
            RGVLYkYrQ3BXMXdaZENzdHJUeEhydVN5clJiQ3RVSWdFZHRrOExCTk9XWWtiZDdL
            Zk5NWnBVRWkvbXJxbkFoWFJaZVB0WGZOY0FhVHloa0l1SFEzc1JGL0MyTGlySzVP
            cWdma3R0aTNPUDFFQWJnREhQcDhkL2FrbkVoQ0diMm90S045TEJWYkVuSUZyVkNn
            MmdWL1JMaXIwRVNnTVh6T1NIYmJ3dXZKNVU1TktlcWJjZ1RxUGVSMnpLZ1VDZwpJ
            aEpSZXpQY05uYnlRQTJKcGFLYzVjOWlXTk1Ja2l4VmgvNDNJUlRHM2E0Ci0tLSB1
            T09JWjIra3FvMkhmZ1B0bTQ3Yk1SQVN1ZHBtN05ycllnaHhCbzlYREVFClPhoieB
            8+31brNGJC1eBaUcorh4D7VFpYSfdzHJlyKI5wqVuGmcZh3plIvNDO25FXSmB7ks
            TJdzA2dznmrGgGM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T19:42:05Z"
    mac: ENC[AES256_GCM,data:8GWfqcDM7/9AirGP02MIyfUJi14eCjQHC/oTt+ZsXAxrAcdEZa9skqqyLNAP96XNjfO5pM70ATex6MOXal29Hu/U4TemkNntOH/gdRpC3po8Knuo3EuKbjkGdp+MYo1yB7/wrWh4FnhsYwfpTsiXoGojxXDCHpybW/6kZQmVWRs=,iv:bHtKAj3hOkDksYYrIWKO41ooCsktvVVyNu3ngaKOkFI=,tag:DCcmfH01aVvkE2gfqaEQwQ==,type:str]
    version: 3.13.2
