apiVersion: v1
data:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:KHoFgw==,iv:T7CFTi2X6QoTw8WOoV8La1C6+4uzAy3oImzvESqhrKY=,tag:Yjlh5EJPW3z8PXTYGq6jgQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:A0TPX1TrGJZwCKk3MD0nCjRsGOTFy3K8,iv:KWyUj2+yDbLxJIBGiDyDqUAzxey4Uw0An6j1yEM3imU=,tag:ko28VceflILbQUc1+gzbEg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:s5kIbVq8rmEsbigz0vajLbal2NSfzB36LAZa2I3pSt51L6FK0wjwSoiOZj8=,iv:GELEz9J8XN4Ogbp/HF8FbtOzMEeOx9JqmarU2nCZ5TY=,tag:PuCVXzYlPKxN3XshBQSdJA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:pmDkSA==,iv:40vwtpiUsmO+kAKH2Nimt/vp0P0iC2pCSaQJzDIxGqU=,tag:6oUZzqMHOAwHB9ytXnBSoQ==,type:str]
kind: Secret
metadata:
    name: immich-server-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFvZkRDS25V
            N3lIajNvdDdDMHZleXBhK0hXQ2FBMXhoZ0hXUzFYbHpMMmZlakE0SjVNdTkyYnpx
            R1FoSjRwQjhjYW5LSTJiNmdGeWJBN2VIekExRlBHUnVUUUlibHd6QStGc2grNU8v
            NXZ4MnZ5ckl2L1NJaUxCNUpabGlHbWh2OTJTSDR0VzFDamxONk5TQ3p5bXZFd3Nq
            SHJGZkd6ck56ay9WSlZocU5CekcvZ3hLc2tMQUwxdlArb3hJbHJBVmc3ajhKY3lX
            V2trTHFLUW5zS2NtUlhpZTNxcDdRYTNCTUlDK1BIeURLSWtkWURRVHoyZGx2Q1ZM
            R0RabnU3Vm5sNlg3QTJQaHpOY0t4Z2RPNk1zVjlCUGJOL1UrcUFYS0oycUFIdHE2
            RVBTN3dwSTk1VUtjMFRTZENxTWNZN1IwNzVmMEcxcG1ydjFZQ1BIMHpEa2lUa1RY
            bkdkNE5GTEdHaDJGQi8xc3l4ZWorWFE4VzdYWTFqS2U2SGFCZkRkQ0J3NGRtbWh6
            bjdDckM0S1oyaHRpK1NuQ0N3MmlKUlI2NHpnQ1NBdnpMd1B4b0JHelUyU1BhUXJ3
            OXQ5K2t2c2psUHpOejNtSVgwdkVwaHlXNGR3NzIzN0pMQnA1NE1CM0NiWFNuNGY5
            dlpvT0YvWXYwWmNleDQ4SS9jUnR3Qm55WWRMTkdrcHNuckV4UUVXSEhaajlScW1P
            QVByam1HQ0FRbng5bk1rTmQ5aURBL3Y2eXNLVm9hVjdmMlI0d0lZam0xaUhoQ0c0
            MksrclhLZEJZRWVYdEZzQVp2NnU5dnQ0QVRDQTcyQmYrNEsvVFFpa2c3cnlUWVFR
            NE11d29qOUNETHhLM1FOUkVzcFJKd2tGVE1wcWhOaThhT25vKyt0UlJuRWJYNU9u
            R084VEhyTEJ5by9Id2dIUk1Za1pkaCtVbitsK2k5b1pvUmpBdldUaWNNLzc4ZWJq
            Z3lLRERKQ1RBYUxRY3VMUEViTDFsNHdqOWZ5eEh4WlZWUGpXTHYzd1Y5YlFqMnpX
            dUF0MFRhSFhpcEtFdVBXeDFHYVJ3VllWVTRiMU5TdjEvQlMvMVNhQzNwdmVJNTRr
            blBSMWxiUG5nWjhUK2RRVElHV2F6dVhoRzdJeUpoVnJPamRWZGhGM3VtK1o5ME5j
            a1NBZ3E3emxFRVZ6dFdsWFppdnRncnZxZnpBV0UrNC9seE16SndzM3lDUnVMTDVN
            THN1MTdDRXQxcU5Hc2pBMlYvWXdJM2Y1b29lampNbFFLc0wzbnpGR0hCbHNqNEdY
            eU56bjh1Y1NMenJlSzRlaDFkZG1PcmhvUEN3eEJEdUxXVm1CTk80cURrU0lkQWxJ
            dUxmNUFPUHdnNk5wYmYvNU55TExtU3ByekRGWUYySmgvV0tMUjN2cU1OQzRrblFz
            M3FZY0dEZW9oY2dya2d6VU5SQXoraUhSMXVCaXUvd2h0NnFlVmsvSFNEekhMbVZH
            VGJvZm15NHR6ajFzSGhjTmFYTjlvOXROQ3RBWm9XTjZTUlFTeUo0bWFORW1jOHFV
            VGJGNGtabVNpQUo1RU1ObUNMK2t3WXVFcjhCN2FMNko3V1owSW1RRjBvaDZJdGZP
            TFVEN3NGbVJhV1JuNDFrdGZIU0dsQTAwQUFSQ1ZDekNXTkZSWGpZRnVPeXd6VTAz
            RWJ5NjlNYW8rRHFxRS9NNGs5ZDZVcFo5VkdCdERsMjRPaUlWN0dJeVBPR21CTEVv
            Kzh2MnVWTnVkN1FxYzFya0RndDZ3Qk0vcHJ5NDlNRnBncmIzS2Z6MG5rZXdRNGs3
            WktKRm1iaDdQcWVrekhKekhYNTBuWDRjY1NIS0hQWkZ2cFVwTnRTL1RGeFErNk9Y
            YkltNXZOS090N3h4WDV5bCswNE4wVVJ2ekVQTk9pZkRGZDdIeHlmTmVGUTRCWEdF
            NWErK3l0R2NOU0lzL2VQTTkzZU1ORnRITkQzb1NYNWRFeHhCRXRuR3ZsSThMdwpl
            b0M0SDZ1L3VKRE5wbnBib3lvV1JVNFRWempaSHdyMS9vU1B2WjA1VTZBCi0tLSBH
            Z1lvR2dFSGxlUklxa3hTcWdOTVh3anpUTUlZYUplZGNBMmVveE1DRlJnCtSREhUV
            oCmi9R9Ic8PrxeVdiB1jiir4aIS/htdbaun3KMu/7p6ZP0rgXonXVV89Rdp3RMW+
            zGpM836i7pn2qEo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T15:07:35Z"
    mac: ENC[AES256_GCM,data:pnnRTgVFc1keJdGXsAPP+aj7LefaVzcicyiQ1MZxet8SDevWLGRiGxSveQ7nZ0MJy0AnaX4X3GctKyhXGroT26g919X246Rt0T6jiO8cNsjA9ZXiuCVSA4qeLf/Igme0NfdA825ocCpHC9aLVlqFYT0PFpD10sXCNO7dZ6Oh8A8=,iv:FUMYLlSIcSbcmTPlMTwnxlsO4HiM1prpR9ZB4zkswhQ=,tag:+7yKk9lIC6b1U8G5ck/+yQ==,type:str]
    version: 3.13.2
