apiVersion: v1
data:
    password: ENC[AES256_GCM,data:t/JaMyZdua0EbYnc2SEcikmZjpGxZIKDNV81lLoQdr8BR/oKHXhgyxwLXS4=,iv:K0uAIGPNk9wqduBtp6Oh9VaJrHIFygkcp9Wpm/9yFKo=,tag:FWVg5DvV7NNZZrvA+tr+oA==,type:str]
    username: ENC[AES256_GCM,data:QY2uLnK+IxTRPCGK,iv:/8HaQBwulBgTYqnQxDec4L2wE/60BaxzwHn0NgsJAiY=,tag:1v15nsjWbaew5dGr4rmUvw==,type:str]
kind: Secret
metadata:
    name: postgres-superuser-secret
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHovbjVEdWV3
            WEZJVEMvT2NNaTNzYzdoeDIvaXhUYjlWYlB4aTFrdXhhNlZSMVBKaTg1Sm9nWXky
            ZUtqOWliajhsQlpVUXI0K3BrYkxubjhxODdRVDVvcXVCSE9XMERqOTI5L1dJMUVv
            LzBseUI1NHdHWHZ3blcrUUxqY3ZZRjRZc2ZkZjFWd2tkbDVJWVRZSFpkSGxjTlNF
            WS9WWlZxMlNUSUt1RUtjdlNDL2lEb3NWMVdwdWtYL3dxaVNraElPelJ1Z0JwNUVi
            a3lBNVZVQllrUXpyWVBXU2dCMnBuVG1kMUFOUFNMVnJQLytIbERrRWh6aXBQMnJq
            bTBqQmlXSVYvYllNbXAzWHV2aEVBNlFxOHZmc0RSeVphak9Dd25ORjRTQXl4NUgr
            dS9USkxqbjY0Y2VDcUszVTZtQ3h2alNiWXlmMFlMckNsVnpJRC90TGVES0RXYmFW
            bDIzdjVFMmVicEM3M0VwS1Y3NDU5WVBnaEdLYUNYa1JEQ2xiM0lYaW9zdlc1OGNR
            ZE1wejhmSnEwVFdVNEtiR0RDbEN2Ym5pMVg4eWl6cXNGK1lqcEVzUk9BOWJVNUNu
            MWx1SjNIRlRMaENYY0w4b01JcGg4NkorYmtpdm1HQ3hZQ2xlQjJ5NVpHUTJTSGNB
            WkVpa2tZaW9DZHpEMk1PUXhVRUd1K21nQjh5ZnBVdDZENDdwbngvK2c3b2I4SW1y
            VHQxRWt1dEcyS3VmeVc5RzB4VTU4WGlQYVJpNDFieUZBNGYvMUk0N3JlMGFzOFRG
            WlkzbUlMcXhJWUVvV21qZFRmcnlWVXhMQnpIaWhxazhMcmNrMU0vYVFVdERFa0Fa
            aDZMTXNvMXhPYWlBKzVnbnQ5NlBBWHFMVGw3MzZ0c1RDOWVIaGxWdmFSUkhWMy9q
            bGZubWdHT2U4dGVOZlNCZ09PelNYc2RTTVdwc2x4QlNWU3VVendFQytFQmJTQkNk
            VWRKcXFDTEp1bmJGRFNMMEZMdTVXVlBxODVra3g2RGlDVGhvc1k4WUpLcGxrM3c4
            VUNCcUFWNUFHdWRzM0VwdzIwTzkyV1RURnJUZU9YWVNFZGVaRVhwdXphZjN1TTNG
            cDBRQjVtdVpBOVBlY3V5bFdkUnpPR3lreWNIRG8vZ21NbDFhN0p5RFNORFhidGFu
            SDVud3doaDFUMVBuNVhlbHdmdTI4QXVvUVZ6dUVUT1pWeWM4aG1HWjlhekd5cXhq
            cEZvejdjRWFZRWhKM1lFQzlyeXZzTGgydDlRcGE5K3VlVzVBc1lNT0xwbXh0dUpN
            Wmttc3RCQmlQQVgxaDVLSHoyMlVGY0hQU21SdzJzMWZPSmlaa2lPZGd4UnFZSzhD
            aVZpVEcyQ0o2ZzdRcHdkZk4vZkVMRi9RR3I4QVFrZ2VJZEVNc3FwNWtMcFQ3MkVJ
            cHNubldpcDl3eEQzdTY1VmRxUXovVG9FQzZlQUpNcFQyeDgxTXE0Q29EODMybjJH
            UXlUYkQ1SVhLMitPeWdJUStwMHNOUkZ0NVBJaStQWFFFblhGTng3UkN3VWFQOHUz
            VlBIcGhWMk9XNXAzT3lqZXF6NmpqRjdEQXJsWlBRejFhcTBPeGJINUd3Z2ZwTHJx
            a2oxM1JaOUcrYzRoRFJDcG52aHZsMDRMbnB2VWx3ZmdhM1NYZTB2eEliN3ZEaXE4
            SjN0UTZvYmJzQ2liRzdEN00zYlBxeHlKKzkzbTRBUnhVcXYvWEZaOW9FYXg0MEI5
            QUltKzB0SUdwT1EwU2xyRThNYmlHRWpMUm80eHdEclpPQVJYN2FoYnVza1lvRHJL
            MnFlMzhGVnJqYkVFa0p1cUVtbnBIbFFhTUYvUE5FK2RCeHQ0YlYxanFTZjZnWGp3
            SUhld3QzK1RMR2RtVTRwN0VIM1ZuS0dGaHFRQlVHU0Q2UmQvVDhLU1FoVURNeCtk
            Wkw0aHNyRnE2OTJtTkhBVW0rZk4yUkh5NG5VVzN6V0wzKzRFSXE5SXl5NHBNQQpy
            djJjV1RpL1NQdnozeSsvL1E1V2FjSmoyc0p3ei9Ld0hlNXhEenpYT1JvCi0tLSBE
            ZFN6MGEyTWpwTWxrbnJJeTFIeXZTVlA5c3dxNjRIU2QvVEQyZ2FuVG1JCvb9CXfB
            kyN+izdhNJTS7XmRewuYm1NvBU7JOcxeyKvOVfGCrSQx1exA2FZU7ndl1x6pOcXR
            /KudwnIT0U8PgZk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T11:23:12Z"
    mac: ENC[AES256_GCM,data:Lz+vkhgPh6bh9T4UHaayVr6oAEBNaEO1TlhzQ8Pkd9axPGUzsJpbIGWf1n2CQp8Og1P07tIZeOGikJ8Z5FNS4EC+Zjge+3uJ8oXoKBKd68ZJjbVRreJJM60sJa7V/81VNz06lXHSdTtfrZLw3y51bb0hXLzhFsB4svqrIIbvzHQ=,iv:F/VjKorVpMIvTjPEVKpkB60pyzpTTUNQwVBmJCEHYbU=,tag:M8A+CN4QPt0Ox8vqJhD2yg==,type:str]
    version: 3.13.2
