apiVersion: v1
data:
    password: ENC[AES256_GCM,data:cwhgqZsn9GUJEAgSNMRN7J5hP2KDrh1Kgd5LkVT+8aYBHDGRgwOLMfar29Y=,iv:HDdashIIU7eNeEHOyAjsODuqPOP/EPruLwxOGZp/dBo=,tag:KoJkN+CYQ817c4KpbO6hYA==,type:str]
    username: ENC[AES256_GCM,data:y4N6R5mPDcUZipDs,iv:PeCOup4g/2CSllQ7B0cGiCntDLYSbuDzM6Q13ixe7R4=,tag:35LPgyzOJkcrE5oSpwm2Zw==,type:str]
kind: Secret
metadata:
    name: postgres-superuser-secret
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICs1Z1JuRXJE
            OHJqWEpzSDRtU0p1NzlEWWl6cG0vM1J0eEtJblJ2YWlodUpsS3Q3MFJnSXIzZmh2
            RHJOd0xMWk5aVUkwVGpsczZ3VXl6dG5lQXFESHhHdjhxWEVjWGNEdUlRRkdwdkhE
            SVluQ2cwUVloQi9yWHhPVWRqelg4ZGswUC9WZXYvRHA4bXFiWlFBd3NES3h3NCtB
            NnhIN1dHSlV2R2lONVNwSHJUQmVFSE9qa0pxamd1dmExbVBsTUp3V1NxTXlIMU0y
            d0lCdGViSlFVZGZSbW5ta2RmeVlLYWtBTlFWY1hSZkI1RDZOZk5Oc29sL3NBNUNU
            T1IrN1ZXME1iV0M0VnZ3QjVDOWdodVpjclNGRlVPQmNXRHlzZ0JvY3FJK0gyOXJB
            WEE5b1loY1piNWgzakxFT0RmNllUMlM5MERPZnFQSFc3NGxqN3c4RVlrUVhtL2VC
            SDZtbmRGVkptUkFvRHBSam1naitJdUhQNzBPaGxzL3FMU3Jtc291Qkxlck1ycWFn
            QzdtWDhvNE5OV1pWRHJkZmR1dnN3aGkvd1ZydDVhUURXOEJOTGFOUWorcEFGWkZW
            YVBOSmdhNjVCQU1kY3VyRFZPT0tnSTdaQ2c4NDB1Z09xY3FteitnRHd5ak5CTGRX
            djNMWlBIK3AwS0kyL2JXN2FpNit6cFhSOGxZbUtYZ1VMbEQ3L01HNnJ3c0lleC9N
            RHFnVGRhSmF0Q3g3eU5JaDE2OXhLK1NoSW9YK1I1bERDTmlUWFo5eFRPZlVwTTFm
            R254NHRGbmZpR0tMSW1TNWVOYXFvV2I2RFFORmxFNFBjdnZ6UGZwcFRVbjVVdU9W
            Y3ovWCsyaUhLZUsvRzVQRTlwbTZ4aDFDYUx0bDV1L3F5MGRKaysvUjZLa09vQzNC
            R1Zvd2RidjgrNWRTZmJuR3VFaWt4ZmRYY1MxQnlqeGpPMUkrSy9ZcHJwczU4T3Z4
            VExXbFpmb2k4RzZvdFdVTzA4WFMwbDRJOWlvMEpGUmNhK2JRVWoxVWtNMlNOdzEw
            aTloYkNVUmRvQ2tXOTV1bDJGN044QjF3RGdCVEJHVXFrQlYwR0RIN2FtK1NLZkh5
            c3JFaE1YMjh2bjlISGZyS2FmSXIxakd6aHVqK3h5ek9HUzhzOWlkcW11M0VSckFq
            N05Ib1BnajY3R0VKNjdIU0d4U3hNUnlBWEJSYkFpUjdyRTVxYm5rSlJ6bWJwWEF1
            RTBjTjJLM1IvTWsxZmxOYW82RnFjL0FzbWd1TnFCYWg1R1NLV1hWdEVYMjQ2b2cz
            RzdwdEZSSFZya0ZBVzdMSlQ2ZEpwRmdmZS9QNFY4Njg3ZUVCVjZENjlWSmltbVZT
            YUhKQzhRLzQzQy8zUDJ0V2E5RkRoRm5jMWl4c0VYbUFCazdoanJaMHFkQ3d0SFU0
            SmtrQXRlMGpZWk9ESUM1TFd6dVI4TVdWbWlIVHhHRHhtMGl3czZKYWtvSE1aZXh3
            YmdROFZseTBuV1RhQTZaZDJML3N3Ym5zRjNodTJHOXZiMjVtTmp5TGFBL1RsUU9s
            TTZQbnVHT2JQbFhYRHJVa01mY25GVkQ0OVhJWkw4bFJHRVNTTTI0bW9xTUJFazBB
            R1hBNkFFaTYzb2JodTRjYWpRVk9mbEgrcWFIdkJhdjdnT2grRWdWNERYRnpjekZw
            WEt3RlArWFpYK3UraStuVEhCRjdvMWcvbXROMk9CQkJHNWFNZ0haYU5YY0szWk8x
            ZCtNYStWN2FlRHlkaC80Tkh1L0cvSW1LWlcwRzFJUXpRRDRSRm03ZTR2SHpmSFlB
            OTFEWEpIU2FUSEFSMmtudU9XVFh1c1ppY3NPTWVWRHJ4bXdpUmhFZkZJcGtNRmZW
            VVNaVm9ySjlVeE1iOUkvYVZrYnpibWZEN2kxeWx3bUFIRnRSbkZObHViWkwrRjZX
            ci9nZHkvM1FCR3hscWpmVGRhSUhVcGlxVko5UGQ0UzZoYWhVcFhQMU94Y3pmQQpR
            MC9zRzNFa3ZCeEdZOEdVOGVIZnhSTWpJOGRpcVcyb0toS0ZjU0R2Q3FRCi0tLSBU
            V1JDQ1VOSUtPdUMvNm5MMkQ3enpvN2JESDVieWlSRGlESHRQS1lvdE5BCrbGNCM9
            LdgbySUI1FidAb/6RVxbUefNuTvOf/XvT6ouaEwhvwOstal537T/K8+w9I89R3Vq
            Nsg5uj10T2iwZuE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T10:43:02Z"
    mac: ENC[AES256_GCM,data:ZcT2s/SFltuZC5/gJfpgE3tPrHNq+g3sQA+y9qwgAGn1PBeGHfCSDR6qVpOXe1T8kT087FCPbBmZTN6B3lm1O0o19hqmuh4OjdTW4y+buUHbxPZjlqK+4vhWJnc+qfEP96VwNL9aZzFDleV+pGjeHuU3EOxHuW5joFNd30nM/rk=,iv:QC9SYdS5Sva7RXiiW+zhuCqTz5OTbJ+BWr0mMhIuTgw=,tag:T0CsoeenSzxLhtDrPDv/7A==,type:str]
    version: 3.13.2
