apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:fJVuNZQ13XqCYN6qIIUqqALtfML8mQPc1lTdBPYFsDSvEJ/lNiMKfKlWjE/YKlmzikrk7KNimLdC71XDvEzbeQlnTs5ycPvMl0kRzW7sb3U5mkV+4M3VZzlTlBVnIgVyRNfPbQolo6n37/wzWv21cAe7VfjZOBMzgk2z4hIm+dlQXyKW67OO2vIYZxmTjuO19C+1wfqm+Gw/S/1mWRRRaE5rgk5LAx01nohwC2RNQyP8+hnE3ZfdSO1LF2RBgbbAYG14Ye4g6uUn08RBi7DjkExzpbH4YWcXnbtBdyCRHPUuiUTHMqYdo2KsgHE=,iv:IG9VR3/FrOJVeVRwH+7XzNVTx7oOXxnc1MauMwnlWTI=,tag:Mdbil45PWbInVT4O68yUrw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBMZ0NqbWpa
            TkljRm5oWDMwTU81WW5TV0lPT1hsWCtueHd4WGcrMk8veUFldW1iZWZTNmhLSGJx
            bUZYUUNFTEt6SGVhV2d1bUZnd1A2cW5CMkQxYnMxOHM0UjZMTm5kcEFJTWxpajNk
            KytubEFJRk1FRG1hNlQ1M1hBbDQ1WDRzeitJV1hZT1VkMU9CWnpkWXJCSVUySHBR
            SHRTdDluTmZ0UTkxR3NMZGw2Y3FxNE1BRjljRkJGM0Q3TVZSOWo4ZTg0ZkUzQjBO
            L0pDbTc0VGRHdVB0KzFHUkhnS3NnWEN1c29aZHBjM0Q2TmZIUjZUdHhMMWJmQnkx
            aXJtbnoydmtsZWZKZW1rQ2oraXlDaWtPOVdreU55SnE4WDJzYTBwbFFmOHNSYzRX
            ODNiRjByTjFiVTNDNDhtRDJaU1l6d1pBVDJXaFFVOGZmMUdObC9KZjYyM3pnUzVt
            YnFra1FqVEtGMWtvL3hqNHFpUVNVL1cyOWRtU2h6UmJmRGpmL0tmQ2ppWjFzaVRx
            UWZkdzlsbU1MeXFNdTRRUVlBMks1MVpzOFZEZWZEcGhCZlFRMFN5SzZYbW9DQTNJ
            UkFGTXZLZSs5VCttc2hWSXFjWG1lRHdxd3AvSFlGNFltMXB6SnVKRUdjRTBTWWpJ
            Qk8xNjdyZWtNaVJTcE0rZHI2TGkwYis3QlkwSmtQQjdWTHhkOGhzVlZXbnFnSzZC
            T0pmL0ZYTHZTRHRxZXhWUWtSZHJEZWZIcU1HcE5VeFVZdGZhdldJR0l4Z3FKSzRG
            SHRYSHQ2QnVZOWZmNEkyRmY4ZUVFQnllUEtTWDF3SnBCdkxld2Njd2c4WEtObEpQ
            TjBaUUtwYTgrYnBsWHY5VDc3UHA3NW1BNk5oU3NOdUtnTVpoVHM5alRkNE5UU2tk
            b0ZQK1p3RWQ3dDJNbnhKRTRRZWVWVHRaNnNWa1Q0ZCs0OVdoZStBSkRQYmVMWGFq
            VzNsQ2hjenJ4VUZ1b3hBUGNLakNIWnFvdGQxWmxtbEJ4U01vWk91Q3JhdHp6T0xx
            VjZsRnFpNFkzcTBmNDQ1alZMR2RYUWtsRVUxdHIwRFhkYldHU3ltRDZib01VZXlF
            SWY4SXo4N1dWT1Erc0FxSWVkRFpLby9HVXRUb0thZjhVbDJFRmtKaWdwUDlObU5s
            b3c4WXdhVTYyN2g4cjBmaytlMk5NRGwxdzhUa0xHcHVPRStEblhEZHViMUtuc0ZJ
            a3hUdHNwK29IVVhFeHZkTis5d3BwZklQamJuZG9ldzN3TUdHY2tvdko0VXFCdk1J
            VG4vOHUwbzFRUFZ2VDhJaGdjeVVDdDdlTGEydjZQdmtzVW5PeTRHSXpZNVZoSktN
            b1Q0VGNsS1RDVHUrcE9mWGMzblI4cUFaUkNaUitsanljQmRnVWR6NWdIb2tRcWZ1
            TndIU2FJRTV4ckZ5VEEwMHkxaHUvQ2RMMCtlcUVNUWhPNjZra0xDckdHVXFJeHZj
            L3FRU3pyOHlnZVpBemtXT01rY3JqMTZuZnlpSTVUU0tZN1BWQkRZUDZWeThuWTFn
            YS9xRHFLd3MyUUR4dEh6ZisxUkRwWS84RzhXYzBVVGpnVTVsVHhkYzU1UWxVN0Iz
            a3VmMDZJUkl3VXZVZmFWSG1mZHZkeGhpOEM1MTdOQk5sUkNjSm9HQWpHcURaV2h6
            V1AyY2ZsR1FtRGVZeGhmTW00eVVJK0wrYWNoOEFoT21RV3QzKzAvVE95US9nblJu
            cTZrczJOSTUwaDRqRFB3dVFtRmJ1M3NYMUptUzRCM2Vjc2ZiamlvUG56UmU3SU5s
            NWV1L0hpdEZIbnRWZ1AwK0ZlWGo3bEdzSzFHaWx4WW8yZ29zdzJxUUhKUW93Y04v
            RmFqTGgxYWVlSHZzci85R0lZSjlOVUwyeS9NSHlQbnRsaElZQ3p5bkxKQThIS21H
            UVlQTUErTEswTDNadEV5MWdGZ3pJS3dUYmt5cmtrRUJMR3RIM3B6MFhONDBWZwp1
            b0hNRXYxengxT1l4ZjVCdFZBTzUyNnlWemVva2xwSUZXdG83NzRMekZVCi0tLSBj
            MUFjK3RlQXZYbUZNMDVZSmdRckEyZ285WVk2YkdSZlBZN1BjZU1uTFZBCgdIHi5I
            2CENV5aWMs3UHOhGCGe64HGj4XTaQWSechUHHE165uXC8aczzcVKjBc87OoKRkM2
            vg/4eunIDlBrzrA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:19:36Z"
    mac: ENC[AES256_GCM,data:MSNGrZGD0rJVgbzTjm+DhO+UhYn7Xbyyu3duf9jdcffBIJOU8iTH620UCHdGcwuoAdFk5BC79ylzy973ijYr4/XEF/fAubsqd1Me2tCSUIIkn/EirVYjs/aK43tPy41ZO3Hg2M8Vnaa5ChiMRx8JyOMnuTJmZupNrhsZNkUHRy8=,iv:4f58tNWWmgrDlE+AFkepoT/f2JwvSMWX2KArV9bMXzg=,tag:9GN0CG1JHZahfjf2TiGZwQ==,type:str]
    version: 3.13.2
