apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qeKXpY3pQW4arTXdr9SrRR5bMuKsI7LKbJVEZtPTYA5wYRlTqaAOR44YBoQBwIcEGAE2gHRN0Gh/xw9i5Elf2OfyKfbzfkVOrX+p6Yk4XMJxncs3S2Xn3IhF4zk2LGAyfvpnRaamItFvrQi57Y3VJrqNvekKzQwrR28Wdm8RDcP2EuJVASl1Aa9iLvdbCquRCRYImzcg7v2h33hzrcyIO5lAgf/ZDKqUSPOFsvnwIP6XV5QY5+2MZllPwpczfbainTcxW2N/u6unM7vnjl1j9s7a2b/4jO6sZq9Tl60pmwPWdIMcmgCD3wKjt7A=,iv:6qJ5Y+Wqv02hxa2daRN5s0goMo+TZ0ynFnmYxvX4PoM=,tag:gg3sdYNIfqlfHSqfel5H3Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR1d2ME1GV1FlaHIxbkpL
            bXlPR1cxeEwrMm9yQkZMM2cvNW1GTjl4SVVvCk1YN2FnTFJnSUJWZWxUV295dXAz
            ZGdySjdwaDlrVCtQTGFJUVhkWE5zQzAKLS0tICsvc3ZRTk1PTVp0dnZ0ZjRWTHFi
            YmlzeGg5VU42T21STVBycFM0NHgxM2cKPGLZ2zjHQMSnOooI5X+st0X1fb/t1kPs
            uuMgUug1KOwMzSs2oYW2OoE5TdB0MAfZYEcXSITW+LOqwqnqC9KCJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T21:01:14Z"
    mac: ENC[AES256_GCM,data:jBW6hd3ViZlJIOccpfF3VehhG84q7CZCVb+dzX0uEphoVv+SPzSVbvEYA7CCq1bfY8T5qPuFJ6m71V4MAxpzPnyPGnbcU+vT3fmwauXOpfhPXs1TG0a2Wyy0HMNsFswjXM33tCKDqvB4DAmzELvwTOaLc25IjQ51nWdTiT10ufc=,iv:F5BX3NswF7jNP6ceAhApFJzhXAuukycWUsFAAuQVq54=,tag:9xl6C7bF/HjEltsYE6T84g==,type:str]
    version: 3.13.1
