apiVersion: v1
data:
    db-encryption-key: ENC[AES256_GCM,data:/aSQTWGJwPzm2hCCKQgswAN4qh7tcrYoNXO6I3aZcbxsEsjD6Q1obktZg4K+jrDyQ+S3nyXZfE0u/OFK5N/MyBdWy3CobqoG5/018SzYo5Lbtnm+RWZeEg==,iv:EHJEJW2aMWa+FMjDADWT2djL1HqfwbjBunU3cVN8Lk0=,tag:P4XWaFLghSyA1RfqAQ5EpQ==,type:str]
kind: Secret
metadata:
    name: db-encryption
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZQbjVleWdM
            eUowSXJqdGN5dCtKeEJieFZFNWsrQmxlSjhEV1NaaWdGME5kNWpQODV4TkhCVi9m
            c1YvZFhSaDA5SE9IMkx6THQ0bWNRV1Q0R3lZd3ErYk9qc1dmWHNnMzdUaWg1Z0R5
            R1N0aXlUWnpZOHhla2RvczNsN0wrRktmbG9JTXh6VkU0Z05yOHVzcm9OalJsNWlL
            QSs2alBsSUlSenBFMUNOYUhEd3NDMnp3cG1SRjlDM05WTEhqditkaFJnZzZRdE0w
            a1dDVmJWTElJV3p0WHhFdWk0RlYxN0R4bFBNcE03c3pqYmdhNkFKWmpHNjZRQ0dT
            SUZnRnZQb0Z2N25SeGdOWi9wTFQ1eVdXSVNOVEdCdDJLQW9TQmRZS1BDdVljbkJQ
            RnBSUUh5VmRMZm13MEJpRExPK04wc0g4Q01RWC83cTBKV0pieG00WEM0Zm4xZEtO
            Q3ZocDlDTzlHMTJTYjE1ZjFLNk5xVXVpcW1aWEx4RUlMMFI0WGdlOFlHZWpIOGI3
            WXM4TlZGazEwQUx6QXEzaTlrMnNueUVJSVJoemQyajJSZHEyengyNm5oL2FEMXpQ
            V01naVZ3MC9abUtxMmFyRjdxWCt0MXpUZFI5S2lPY1ZaUTRBWlF1Z2FNS0p1ZEIz
            WUpmZEhBQTB3Qjh6SzFWZncveHd1SkVKVE5YdGl0MnpNa2l2ZXNOQ2lWL0NkN3pk
            QjFlbjlQRlU3TUlsbjVmZXRjZ1dZcWRZR3lkM0lRekhXNWFROVA3UFJNSkNxTzVG
            QkE3VDR4ZHNRUkNlVXpOdDVtNjl4RHg1WnRmdHJhK0J0cXZ2cWU2QnZ1T09JTVhi
            K3hTV2JxREZ6ZmdLSnhHRERob0hkTEtSNDFBVHRvc3k0K2VQN1lCd0lrTlhiTVk2
            WUpkcVgwZlFkZnd3ME5ReVJCcC9JM0d4OUgvbHlyNTdiZVF1ekZINEZhMjV1VjYx
            TGlyN1VXbDNQemZCMVhNbVBIczkzdjkxNzE1MlFwNnF6cVA2QTBGZTl1SXBUTSt1
            ZFkxbVJDYUYzOWVqWVhKa1A0aytHMlZBaHl0WUlpc1Z5Zm5veXRSYW0zcWV4QkxG
            NWFEWWt5WlhXTktRcTFjTitHYnFzSFBmdUltaDMxK1JxdzlSdkt3YmpoRVJ3eERL
            WlhTeWZER2RCeXpIcFZiT0JXZ3hZeDJEalpMczBQdUdZVmxlcm1hdU12STRyM2py
            UG9NNUNJQXdjZkxxVno4cmRLZXdYTUZGWmRBa2tOam1ZTGtROS81UmFNQlhLNXlq
            VW1FWk00bTZLZWJoYkRzaHlSenR3ajJSUUpMY1dGOXhQb0RSUHlFRStmaWRqNkNs
            bFNkcXF1bjl4T0NlZ2dJVlBQeHgvNUN0ZFN5Q3lETldvMC9DRlhRdG9kMzhXZ2Fi
            NXh0QVVoRGNoK0RKZ1ErUm1vbGh3RnB3dVZsTElIQlNjd3psbHNUT05YOTUwYnpN
            T01zZGxKNEs4bEd0ZlZkeGpTdG9LSG9KeW5mQmRTQVZaaTU4UW5DT0xUcDRhM210
            VmFGaHU3R0UrM2VwbWQ5RWhmL1EzdGEvMmVjZEM4ZUFRZUlBV2JSK2RVclZFSWVt
            UklCWXNQUnRaQkJ0SERpN3NDaXBHaEtRSkFjZFozYTJGcmlGdWVtMkRPZGlCdXVU
            QXU5VGo1YzQ3SmgvZE9QMEU1K0NwWFdMWVJrVlZWZ1FubHptbXdkbFBtd2FVYkdj
            dUNXazY5TjU5Yjk3V1ZHUS9rK0NITlJ3RnltT2RIWTBhM3NpS3BScTduOVpkTHFq
            VUtlUTdjQjRjeFUvejNFdG5TNEErck1hN1VnMUZqMFBublhlMHM3TDZDdU1Hd1Js
            bU1zS29oR2JsVTYyeUliZFhxOFRKQ2tzRzBIdFNUUzlwUytTVW0xY1FIZXVLQk9X
            S3E0SFB0MXVURHlrbVRCUmEwTVdENVdTOGdWejc3VmFYbTMwd29zbGJmd0JRZwpG
            dVVPZ0VnWEdNajNyaTJJQXlxeXQ5T0M0UUdCYlJMREs3VjMwSEFrcVdnCi0tLSBH
            UTgyZ004UHA2WDh2bkxFZWlSVFZHcUY4ckJXZis4SWpsZnV6ekVYWE9zCr3Wtm7u
            so27QhTBmJbwDrOMBCSOgR2eHiINgHJDw40rWQmSwzhpXZwK4gCKv5Nq5w8c8uYv
            mUlVpeth4ymRRQM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:19:42Z"
    mac: ENC[AES256_GCM,data:QjtM/yKaVnGr4U4OjZOc9EGEJ4DgRyiNJzcI2yZJQDRtXezZW2EzwOKr5/sSwmo8/w9GBrfFx1NzFvuvbd9tzOfrEv3LEF9JGe63jJHNbIvvNNqNkv+iVlKPPfm1YHsdhtoTPUs36UWYypHCdxKOU6iNfzh4PmSxW3uf5C3a3ow=,iv:FwkMCK8OmoN6/PLcBWuq2gVwecWtelcaL7bQQf6kjHM=,tag:qdQDZdRblhVbRxC33HWMYA==,type:str]
    version: 3.13.2
