apiVersion: v1
data:
    db-encryption-key: ENC[AES256_GCM,data:Xz7OMUuOm8j7aHQuQnOgWgj7Zglmo+txFgDk4LgOYmeQ6nEbmIPgHDVUQsNYObQgAvaJEnOQQ0HOmbcnfzrdXGZ90DBi3FTKp2rnaWXv32aClk1iDDK+/Q==,iv:die96JD9uP+9xg2GnWqkqbziioAd0MZ2Yv1C71gpEYs=,tag:txAOnOFU2sKrjmj5Zt1lLA==,type:str]
kind: Secret
metadata:
    name: db-encryption
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQm4xTE8zQ2lVSkpiem9V
            YklhT3o2RktRcm5IcXlZWVNVUjhPV2VzTlZRClFtN0s4Rlo3U01ha2FxaEl5bUFQ
            WXlqVzNBWDVjUEppSVdhRXhmWWprYjgKLS0tIGlpVmwyNktyN1R2Y01obUhYZzdx
            dHFRRFZwYktJVDJXa1hxVHozU2Z5S1EKvvHErTAzOC2mfC/LlVgz2pl0+7pFtj3z
            Yzps4KwlDM6ViOCSJI0ibxlJK9n8SZyzUF07yOoRD/ke/YgzHlc02A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T20:10:29Z"
    mac: ENC[AES256_GCM,data:ZsgI4WI3E0haH16NNk/ktNSOFzVMrnP9IZ9tJJYv7TpUCeNlFGegxg3xmoovSoaD45zut+q+fh7tsziBOCP9COMWVOSFeEAh0F3MhUq8OuyUFUHpPvlosyZN8Np+Rm6puy9LUnWLnekcfoaQRZoUcvFSNg2WCr2OIZ042SY8i9s=,iv:GycmwSlHt1dnQd+t1WvVb5VK/+QfB6z60ul/dXSussc=,tag:4QO7NvAW9BAcvy2vr0/oWw==,type:str]
    version: 3.13.1
