apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:Hjdl/Psi1uljGUVOmIDjvCHv0apwXMFHGvu8jOQr9XHBlzhTA8Y6YHM+59BLpVuXtSr1WiiiRHuezJ+j7c1ymNuVz1eGlFtnnxGMNZgbOGN9AN21bhze+sVPORusaP0U5vapV28CgK8Lv8iarESNWKS7ujq9EvT6oSm7iNU2uuNLWTEqPXussJ32yGDD9O2VMBr1z4b0x8IB/XTeRr6lOyqOibeiQP/KyQ7E1CbMHcz/38QJk1HozFrqbuM6YUaAGRTsCg==,iv:9B100smryXUlANFd/KhWmc8yL27hY0ONbq7PXFWXPMQ=,tag:j7NB3PyWfF42wj65IMHkLw==,type:str]
kind: Secret
metadata:
    name: couchdb-values-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTGZKS3dWSHRjRTl3TFFR
            OUJRc3k2Z2J2VE4yTFRSb1lXY0R4Mk9iTzNJCm4vVkNOVTQ3aXZXeWtyekFuNmRX
            RWRhM21CTEZqMTdIZElCWDE4aHJSN3cKLS0tIHdzVktqK2syd0JrL0JTaldlYWJE
            Zk53dnJuclVaWTZKMkw1YWc4Wlp3UG8Kc+lyh7Gay6a1I/ehkoUGAu2urLOHq0du
            m+Mjb1N6a2KaCQCIx4/DW1T1MjCJIOriNZhKh3+wSqRyfJxR/8VSQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T07:43:33Z"
    mac: ENC[AES256_GCM,data:gu7Mipuios/1Q0hHP6hyWxoHkHVDUy/c1pSoaAQip8WGpNYYBpHoZGGtfapgr3W1d7URpJcpLtSLLjs8o8rBAO6RGVntnP1ePRy9Ih84XiFrQbYq5xHffJaB7iydxxN/8UStts7/0Kx/jgmVUHzwW7CzMq6Nch8yhYvs+dcLZZs=,iv:kvYdHPRuAk5GsEzNWVQvq1Qdw+CmZjkEK1JGRDxwaDQ=,tag:WQeoy4lwLgO/fS0amL1K+Q==,type:str]
    version: 3.13.2
