apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:8I2yTcen4RFjCOw0UDvEIVyFrEjvSDI5sUfxZBXbTyDw66rcV59i1cdjsQF5OXXaLh195lHyfpUpSG9H+ON1qWakEho0fsP2xKUatqOO+YzshJUibW20SMmOuzBZsC5Oam1F9dmMApPL0RJQorPVJsoFoT38LFrz766dp4ZtT7v/S25HMfeI18CAedGWupcmX2um776SdoxgoaXxxBztTniKWxVtQciHvwUDVhfxTKqF0uUTLLzDQEvWH13413644eg/PPoKGV7+at1E,iv:2v6Aa0TbPsKTx8BhRj7FE0YVq67ZMmMNbTbJmILvdUE=,tag:32CdBxZO9N/JN5Fh57zikg==,type:str]
kind: Secret
metadata:
    name: couchdb-values-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDVIREErQ3BZ
            N0VZTU4wVFgweEZiVXVQRkRZUGxtamR3SWRXc1cxRW1wcXJFUDJrMTJCWFJEeVkz
            VWtEaVdjNElDY1NHOWJUZ3FYY0NrUG5GTDQ4a0pEVnpaYjZvWWNpejdoT09iTlpq
            cjJONGlqR04rZFIxU3pmMHpSTXJ1NkprcHhmTy9ScHA2eXpzTTBjN0JleURMTUlQ
            VGRzcWNxQTZFTllBUVU3aXhSUDNvNTE5dXZXeWlPa3c4cjRNem95VUZPN2doeE1H
            aFdKNlE1YyszTFYrWllUckk2dXBtNTlXdXY5dlFZZjVvQ3pCbGNCV0cxbWphUGJj
            SW1hbVVtZ2QxVUo1dkVab0xqcWFiaThpV3dtS2E3VGU5K0ZVS1dZU1NKcEJVbmNX
            ZlA3WlpWdkFGWGRyYTYveUQwbUhoMEZFRjRBZlFDaWd4cmtjNFlvV3EwSW1qcTU3
            Tm9TM0tIMWhqOHBJNnhNb01rMlcreEc2QlhuRCtnakpLaURYZ0JUNGI3cHNqQSsy
            c09KeFcxQTh5TkY3S3VWeWhXa0ovNk5JQ0hDN0dWRHRFRmlPVHMxa04ycmpVdi9a
            eUhIS3BrQWlLajNuWk9qeThZWGd3UmwyY085STRuczFNKzNRc0ZTOU4wUmNWNGp3
            eDdJNis2RVpheVBUVXRKeTQ3NGhRYk9zaW5wMGt4V3dQNGxKVUFzMlZhOThHczIv
            SVVhdkVPNFU5ZWsyTVk1dVVrUnJrclBjemNyK3dpRnp4SzNqb0hlYXZlaDRGZDg4
            Z3AzaWorUmZnT013eEVJeTNGNExCYUlMZ1JVWEdSeE82OE9WSmplZlcxRFk4MmRa
            bnlTOGk4Tm84emdSWGtid0V1SjhDVUVld3d1UEpTUUZ3eUFZMGdBTi9pQmpxY2ds
            Tk96RC9hM2pPRi9VandFRjdqY2VYQzl6WWdJZE55WW5mMXdjeDE0Q0RBVFJJOHgz
            VkVRV2dhSkxqdG9ZcmR0MHZpajBvVU56cmpZVit3bFpmVGdzZUtFWUFsNWhmaUhs
            c05RNWkyc0hFelg1UzVBWW8rS29BOFB6QWVsSjgxMUszQnNleUgvRFFMc2NYeHFr
            akZDWUFYVC9mdmJTeDhPWitwSzNOQmxEODdBVmhMd3VWWGRYSURBZTl4TjlqUmdV
            RHZwTXlzLzdORVlNcjJtMDljRW5UV2gyNDJNVkhyWCtCellXaVBTWU82ckRuZWk5
            VkEzZmtPM0RVTzl3U0QzeWNPaTgzZ09WSDNET1ZSNmhRdnMrejlmR2JhSXAyRVN1
            YzFtL25mdkJlZnVCNStqUGZ6RzA4VnJBcStJcHo1OEtENFhzT1U3UWNYWjMxWEpO
            TlFrSUtFbVVpZFhUYm00cmxKTExVYkl3MVllU3lZSUIvTTR6Y2dJQlR3K2ViWHRN
            dFEzaFFCWFhjUzJ4T2JWa0svRW1mUTE5K1llSUtNVTJoUjU2YXJZaTQrVGgrWUFj
            ekNCQ0I5bUtyelk3R2FXWVdqOGFUdWpQQXcycS9JRlNrVFhoYnN0MzJXUysvSXhU
            bFNSdjJtY3pqdHZhZktxUkRyN1dSb002aUsvTlh5RHQzMGwyUHMyRG9pc2I5SGo3
            ZnB5a3BQa2M1RGZRWC8yRlljVE9Dem5rVnNzd09majJHOUJJVWdCRForOUI4SFVN
            SmhCbzYwcWlFbXdOaDBNUUhDa2g4UHl4YjM4V3FtWlJ4ZVNGTW5JbTdNQ25ZdWFQ
            RFQ4dy84WnJHMlN6MUkwVzNiVnpPRnNyNm90WWovZE5sSE5lcDFLcTZtbVlobXRS
            S2QzYTljaEE1VDh3Sk01MFZ0MGlIYUlWUCtmQStmM0RsUW5nbWFWNlR2SVdqWEVo
            em1hQ3l6ZFFKaGloZGc5RmVCRHJSK05WUTBWZENTZERDNFFMeERzM3VLUVpvclkx
            ZnVFN29WdkhpWGN0NUtQYkFBdGVMR3lVamJnTTBEQUMxMGhxZC9ZNmhhVGdmQQpG
            OEM5TUJFaERMeXBNNlEwUW82Ui9qcytwVkxhb1I0M2RKRmlGd2laUzBNCi0tLSBo
            OFkyWFZ0WFVFNUpsSGh2Q0puZFR1VUpzVnplT3IwcFlTNnozd3FpOFowCvb2AHhy
            KZAEcfNOI2eH9Mj6sxjDbqxTPvm4/RrMPWyoT3xIbTKDFRqY2cgCS5mE1I1V+gCA
            l1xcxX72ri+lnMg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T13:55:41Z"
    mac: ENC[AES256_GCM,data:sKgdSmlaCDQ5w7bTYUwKTKqXPy48vrANnTZFx+YwbQmIPz/WPh/6pwIhWVzLHhGgw2GcWNVQHFWMiS+bomCoaXWaEI8BClFHLjiKNbDaLujAxLGsqx0hU37spg2/VX2ju3sFRqpaVuWri9LLF5UCF3tNhK7DdowX5qVw790z2MU=,iv:RFA7oaryeXGSpyHaauo+E6mKS3axoBEoY9JCe+ejr24=,tag:juKCKbypNuVQT3QbHQA1CQ==,type:str]
    version: 3.13.2
