apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:432tRoMrK63EH8ZJTTeBGmJJWwgf/I6SbVb/6iivr0v+lyYIEjp/dyfLL3lmOWsKPA5Q/1Oi/udnjsi7mK4KNw9s0XudzCfl33+BHkGdQbtfH8fhYXLtwrhmLOAPSdzpANkj2Mm15XQ=,iv:v41QBHkfbaJpRd/d76SAry/hA8uss1qToVGFyG9ors8=,tag:aAj1lHrQwUIT/C7qwvs+ZQ==,type:str]
kind: Secret
metadata:
    name: couchdb-values-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYmlRU25ZRVE0azB1NTdz
            OVNyeTdaemVQNk5oVUJFRnVkUkRnRzVydW5ZCnoxQi8wc0tFemRJb1BGWURCMU1Z
            YzBhNlMxUHRjaTRwU09td2ZiVDUzY2MKLS0tIFdqU1krdTA1SjBDZk1QYk5FQzA2
            S2dCTG5acXJGSVRxYk5Iazl3Mmo3bjAK0SLcZmUQ7Lul5DRxdnDfwC20PwbsqymO
            PYMQBmjl7jiDKlOAoL15nxyc7nlphneo3HdfTh0QUy2CH9uLAO8pVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T07:04:55Z"
    mac: ENC[AES256_GCM,data:sY0V+u1MyY7BCcYGHucaOJSC5BQmGAwwWpiLEoYc+XuQ2GcSUQK0VFdt+sUs295leQnhw16Le1cykFBj9J0JnVbe26t1MERRB4k746cgcbGih6UhEC17FBk75NcUbESebVSuupNNhkU5ogf3FqzpCjbLjYCs1Fy5kaID+jmc5lM=,iv:iXriFKxbvd7l2eSoiADFiBJbOW4xOXuh3OHSQnqgt4c=,tag:ff/FJj80M2HNAMjqwdabnQ==,type:str]
    version: 3.13.2
