apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:FwAYzbWeXk0BdqnAwGXASQj75yhxafmQ4OzcmqdTBH2y9+TMSxX2qE8N5PRr2MT+cYwLp3dSDB5lHvYmjasqQzFAQLnCJqaG15H+yY2FWHKSQ1bcBTQmTM3c3trJAO7O9vXenpDnZcI7LTJmc5KQ8JAdCglTmb/s4sPempMpzJcj9HFP8I9u+QoQ1d7XcSbmcfNDQI5dsoKlAis0AXk14vopPLhEjL7tGSXHxNshI+CGdYpAIqu5kbFlGL7PVxOd1/Ky2QdR3IcQ5srkZSvj+tMWXkRriws+nW4hOVF54Z+rfsKJLDTNsyqTbDs=,iv:NUDjXPjnZPs87a7iIIGi0gxF85ujstOEsMzssVQwIQA=,tag:mVlNscw9M95+bDoyDzYgCA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0J1aXVxckRQcHlTR2ov
            WWg1M3ZsdEF4ZW1Zb2pyNFcwMndBZWpsc2hVCm5vNG1IV2s3dXVkWGNKZXpRRUZO
            TWtCdDVFL0dSRi96aVpFRlhHcHIwK0EKLS0tIDNJTXdISmZXNTZrVUxIRFhTdkc0
            aVJGMG9zeFMyc2NGWFZEYzRhNnlsM0UK1ef1SXG4Ql3Cohj53SWKjJz3d3dgqAmQ
            UuUY2Xp0K1J5PySee/Pu8CVfUbX7lV2WJhBlj72Jpe17ypLyH78KRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T15:46:02Z"
    mac: ENC[AES256_GCM,data:uzMA769mTyj5V8xBcsToRsImuaQqypphiwvOAaroFob3GLw0BGApwlHDZJFo3qk4fsIehgOxDEjXLNdPo6vHAv5mr2eMsub6R1gtU3Tk3nYqZOtZ8L53zV0XD8NRGqrEcTm1lFfxpmg5HAaGgRt1TERWerB3O5Iz1LVutqxLzng=,iv:mJ+/NXnDzdct6ypXJrMm4EihVbmN7IbAoImfi0dTGg0=,tag:oRsmw7Af5adTX0oCUOobBQ==,type:str]
    version: 3.13.2
