apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:EFwKZ1e1jKeqeg0yB/8/XrChgCcAqlnmgzVUCwfU19kYxcXmyOy26f2JiIrmMjValG34DOV25gErrSu/iMbUfWH1FWV1kL9B4Rl5C/SrGDpQf5c1m/UL286WcLlkcw6SsNEQ0MaVvRlMpr7seBA5ZWq5VqNt+To+22xX9Ldy3m4HFPsT5oIQd4PzLnplnWVLACbLyJvAfwiZxMTSaLhpWOye6hfx5vrD1y2pJXINhnr2jkSdSgahkAzwdJocsRhWD3c7/efcSMbg3pKbTNxnj4s7RWhz+HIGh8JX3DRF5nRRoAbuZVXTTcLhuk0=,iv:2kBtQwD7XKoSOleEMELwZDhJnk+y7GyZDn6mN9LlB0U=,tag:89ULHHlYrY3dN311uC8G7g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJ2WHZKL21n
            eStiZEltMWxKTWNFRWlFeHY1ZFlMRDM5dkVXTDZ5QXBSOEVoZXhMeGp3MWNaQ0VU
            UWR2Tm5NL1lpdjN6V0dwakpXV0J2dVdSb1lZdmVFbHZ1ZTNISGdCV2F5ajNibzNr
            WG9BMWUzeWxmYU9SejAvZ2FwTDlDK1ZKc3VWTVNURE1MYkNtdnpieCtzVXU0L0Ix
            TUxxL1d5MXg3UWdDcVQvcFcwalordnRUditGY1VaNkRDaWlsNEJDYldUeExoRWpw
            a0luWGNFVnVnUE40L0ZFdmVRVHBYeTg5RGRIT0lweGkzS0k1R0FIeWxWdWJHUWF2
            UTgrY2NNZjdmNExsYTBNVUF3V3Fnd2ZTdmdrSkhYRXNVbEErN0JjWGE3aFJIaEh1
            cGY5VnJCdWhYYkphMGpsRHZZcFg2UVpzaXJXbURnWGhoRWl1TDF0VEVuODRqdFdE
            Y0lTQUtyek5PUmtGUnl3ejBDZTlLUnlINFAxVWFVS1R1VzVQaVZxUW9NcENocGw1
            bnZJUEtmcEdZTG0vdG1NSjVoUTJ6anRpR1p1UG9EQldrRFhRVmp5c0dJcVVVNSty
            Vk9KZEo2aVZ0TEc5U3U0V0NOa1JDZm8wNlJISFFNRmRPSDlNZDNjSmNldHZZQm9C
            ZjdaWXpNeHVlemFqZm42YWdjQ0lSYUNpMHBLU1JaVk9GRGYxS0J3dUlrcWFHTlND
            cXFzMTgxanhlWE1nQTJlVkpVZXluSklBT1hHakJnU3lPSW9ud2tZY0tUNHNHcldk
            SXFVem5zdzljSXJQZGxCRG55SXA1SWFjT0pIUW5yUmJDMVZlRWplRFVvUG00WVQv
            bmpSZHlSdUdsRFZWVEdITlVyL1IyQ1NtdVJML05MTVQ1RUJZZjZaOE1xcUUzL2tO
            M2NtOHRTa0d6RU9ZL1dYM0dPSEJscTBJcGtBa1pGYTZFOTBrbStLdXAvNSs5RVZZ
            azdoRCtzdzFlcDVubzF2WStkSFYycUVIYXo5U1JKWWNDMHNNQVpnNnJpbVA2eUtj
            NVkzZHhQbWVva1BnOTdseVNYQUFwTkJiQVE2QzZkMGhZeUNPRmo4OWhKTjN0R1k4
            SzVrNWJTblpuT1ArWHE2TlpKQStHZzFER1ROdlN5RUYyb2p6cHRvV2pVZVZnRENF
            RDBGMGZrTzBYOVZZeG1mQ2JNT1g3ZCtBdHlsRGNLTk96SnFrMkttQTd2YmJocjls
            YWdQdmgrdmxQbERES00yNWJUMjFNcnFwUXFXakFleE5hTkdWRVRqK3hmODZzTk4v
            eU9yZk5vbVBPaGxSTDk4TExwa2E4SmdMUHA3ei9DbnVkUzV5b2VXd3pUdHphc2hX
            MkRQQURDMmx4UG1VU1dEQng2RnhWUGZoZVdyNkFZMjA4eENHUjBFTWJhUjZnUGZk
            blU4SWhyVXlKMW9Zb2FBR3dGMXo0bWE3RnZlVC9RWUt6OXdabTU2dEpLMmhWL2tO
            MkJla1ovNXFvK2J6a1pFY0l2cnRQdVRSODZWNDVSc3I5T1k5WjVnLytOaXhFS215
            VUREVEQ2N1pVTmZkVjJjUmRUOHgyNVIxYmdteER4VElSSEhUN1R0bkNoTTg5a2FH
            RUNwSWV6Nll2Z04rd3NSbjFtOGNqRmVrT2diTUtMdm1XdmRGSTl2ekxBVUFvTnV0
            NlcyZi94dVlxM2kycEFFVFdkc2V0YWIwVmtjWmk2UC80S21pa0ZBQUpnUmtORWpL
            NXBsTnpabWZQREpRNEE2T2N3NHcwMllNTHdtcndvbWZnWTJwV2JhMC9JbVo1bGdB
            Ri9LOGZGK0ltcm8wbTkyM3VYSS91bmdZdmtWSllwQ1lPZUtOMldpQk16dmF5ZEZQ
            cDVlZUQ4RGhneTRpWHVDWTVBdldZR1IyVVY4RkkwaWxZRXZUS3hmWWhwRFZqQ1VI
            eERFTWt3bEFIWVRxZmtFdlArSzVtUGJCRVR6RzNuWWNvdmNpeGlpMmNLVnJMZwpW
            d1ordEVZSHJhQVNhZVJmRW00ampkaTh4bFk1Y2d5ODNKV3hHamtYZmwwCi0tLSBt
            d1dQZ2pWUlU2eHpONEw4WE5pQUtQa283RndPZ3JhcmxzNUJZekwxTjdJCoqWqNmx
            vXkHDQMddHccLvTflYTLsOUnU3Okf7ee6SmSTXquKUVxWDjfRpNcKEpNDmREP9+U
            VAmS531as3H7CDM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:18:29Z"
    mac: ENC[AES256_GCM,data:yvVXceQ1Ih9RLjMiYrPUrfhyshyxiRI9yAiC6Kdr/0ygoFs2gdF0dnrLAAyF//sY0XdPn1UAOkw03iXySuA44iUOsqyMWxI2y690WPm32ZeUGRmQ4vhoDeDT5DLSs1ovnqCbTCGbVKWVCSh5wH2kr7UzlGD7FeHB466TDjJBQ8M=,iv:dJdWmpA2ZLbmQusBN0/Sq0WYVpQ3lr4Wb2RqwONTXiU=,tag:KM8JNJ3EtZYJoE3E0RDDgw==,type:str]
    version: 3.13.2
