apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:xMxyuohNgpB4hu+jOfkyFDycHaakDvBw+LQ6K4YNJBHL5NA2v+5mMW1T838z6ctqLtffFquogkzFeMtV7FAQ6w==,iv:0PxLcO8aR/OG0XrrE2pWY8GTyAQZSQxUZ85d70Rafos=,tag:EwSLGIIoZ9iYOdcehU+Lpg==,type:str]
kind: Secret
metadata:
    name: basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaU5KRCtzSG0vSXUwSWg5
            L3RhaGxKZ3l6bE5iWFgvUGtSM05PZGNBSkFJCnlSRnVvRFY5YlFOdWx4cmRlOW9H
            SktFdkd1eGVpTnBZSkJ6NEh4T2xaSzQKLS0tIFNIZ2Uyb1ZCd29vVU5qaDZibTJx
            eHdkR2RoYkc2SkI4aHQ4VHdKRXI1bG8Kac2tfKMfi4V3qm1dcq9oKry+mThZQscQ
            9CPd6wCslZh4z2z4a6eL+GEDsia552QQwFUSFcT06Sz6Py/kJGU6mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T10:46:04Z"
    mac: ENC[AES256_GCM,data:cfVLYMr0iIU4voSA/J9bRM9cxKa2qww1E1ZQ1MAm5mTJ1oFHgvnyep14+OL/oK4byIq51JfdSNXxmx3KF8cKffr7q3H7kGE53zz3G528/cD6etKDwjbVIdgmdOPSmTu+KF1PwXwKX+PUv2DkmR90hjIQkFg8koEdW/Y7+EkxY0k=,iv:WfNy9WNYgHsdYvCnJeX6OpxbOdk7bDZ7963mOddFO/A=,tag:rvFXjfW5l2oinKhTC9W4tw==,type:str]
    version: 3.13.2
