apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:8sNcrEhrAK80DbUFsJsL8Xc+n/1VbOQFJFPUU0V4o2CEBUGjRJVaFz07AzJHs9me9QwfGdQqFS4zLUrQbjvnEA==,iv:a8ROgI2KbpJ6B+GGJ+3S/xm4Ttlj/MSBCWp9xLVT8d4=,tag:BKsNq0IN9i7NwSg6P30vhA==,type:str]
kind: Secret
metadata:
    name: basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRjVzEvSjdi
            bW9xTndLMmpteWZwb1R6VkxLdDhMc2ZjNXNGZkhmYlZiZUU5ckpvL1RqWW5SYlVE
            d3JHRTNnVkVPQ3RaUFVEQ0JUdUtvb09nTk9kRG5BemV5UUNsd3l2N2c1T1Aydlg3
            VHBsRkdDWC9Lb2VqZGRIbXIvK1hHeUpPcWc2OWFscTNKMC9WUDg0eTVwOWhabUJn
            eUxaV0xJcHZ0RGtBQTBqV1NSajBUZSthTDJSSUpPRm5ZY3RiNTZRaUtFUElrT1ly
            b29kb2Niekpic2hpUysxUUxnYTZTb1RrWU9sQlNRT1RYQ052TCtRdEcyTDdlRmNq
            SXU3TUZyMGtSM1RRbXR3R3I5RTJ2RTJQUUd4UWJsbmswZjNQUDRUa3lwVXcrb29h
            L3hRR1FUNzRpU1E1YUp5SkpXN1ZmeEdxSFZBZGd0bVlFZldURzd1Wk9Mb2IwU1l3
            VXRvLzVBcE5Yd1Z0azNFMzNOUnlocWVkOHVUWjExSEdvU0pnRElhTnQ2N2k3MEdU
            RFpINU9CMzY5VFRiendrK1hLNHJLY0U0cER0ZlVjT0ZWS2VWdDhTTi9vc0xidGZa
            QVJBT1NPdDRrRTBBL2RQMXdXWmhqLytoZXoyRFcyN2hkUU12U3NPTDE3S2g0d1FG
            N3RjcDFpYXJFMHYyZ3JyUWFMZnFPeXRPZlc5T3NxNXBZR0VhM1U2aitacmxMTUh5
            OTk2aUhMTDdFb2ZINGFXejNRZitNdDB6OHlkNkhvekN2a0VLZTJFdnBpL0F5UmpB
            aTZHMEJwMGZkSXJCQTJtZ0FvQ2s5bWVRYTZLSlY2NHo5QTFGdE9PYlJYZWZ6NVAv
            RWlJRkNDbE12aDhnb0QzUmE1NUZXR3NBcTh4SHd2SEhnS2gzS05zT2VtejhrTHhj
            ODRlQnJFcnRZL1AyT2RIUWl1N1h6OXJpYlZCYkpzTXhka3hlaldPYXBlR213eXFN
            RUdISFBneS9SZCtENzNpRkppM3FLYzhOS0tOSUtsR1llbnNQQ0NMRWpFcTZCN3Av
            eGdHbS9WMXBlWTBGeGN6ZnF2dlkzUGFTbEp0NDlVSGxUcXdyTTJTbk9rUmQ3Rkpk
            N3IrSTJobFRKOUk2cVVLd292U0ZuRXJ6cU9SbytXaVI4ZUJMbUlQUUpaM0swa0lq
            YkY2ODkycjVDeXF0eFhBcnZJTGcyVFk2TzhFN2laakdMQk51ckpkNk4wcE1SaHBr
            M3I2amJKZHhRSlU4eXdsc0Z6SWpVZ0doSEFIWXYyU0xaWlJwbVNtQkNSUHBub3ds
            MFFZYi96em1Da21RVVhuTXlVNEFnaVhMbFZNaVc5N2lObG1udDF5a2syTkU2NWR0
            cHYwZzhiV3Iza1hDSDQ2ZGJ3K3RqTlZ3ME9zdE0rZzhXc3Q1aTZhWFVqc0E2ek5Y
            QXZGcU5pOEJIWFlUc09EN1hOYzV2UXlPMXJhekRzNzloRVh5TndUVE0xM2lWSnRX
            bFlhamd2Q3BaNTZrZ3YvMGpiRzBwOXhCVmR0dDh2ZVNaM1Z3OUlqYnYzMEMxNWox
            WHJud0ptQWRLajJLdTdJWThkQngzTWFkRFowTkdPTjZQcWJGeGIwQlZuNkdEQTJ1
            cUtSdzBrZVQ1bXRQSGhKajFmUmNuYncyUWJqcDVYc2hWSzVqMU9ySnlXczU1OERn
            cUVMR1FEdVhUUm1EbW4veWsrejdFNWZiUjg5amllUTEzZXhMNEFHL0w5NmU5cmwv
            c3Avd0NEZ2h6Um9rNzc1b0hOR01pSzZLbGJDWXJrTzFYSVZ6SDhqYkhheFdxdjgv
            YTFjWUFlV004WHJzNUhpR1A3b0NNczhmRkY3SDI2U1VFZTF2TDBqQjEreUlYM2pO
            WG5OTGh0SmdiSmNNQ2N1K0djTEcrcU1pczJ3Ty94bWhFaGdHZ1hNb0pwcUgzazBJ
            cFVZbDJIbEg4QnFPamJZMWVGRkVIeFdBb1FpMUp0RWZoakpGUDJYNGdFYU1ZQQoy
            WTd5QUNjK1N4d1pPMDZVd3MzYkhpRnpYNHQyeFpiQkpuTUpvMktweEN3Ci0tLSB3
            eXZpM2JDOUFNSWJZQkVXMUN5NUsvYjJ1L3p5OWgwMnlhdWhRTUdoT3BjCgfoSwKr
            lfnegR1hmLpHGvr9E37dZcxSx/ykVOFhjKsS5LzYQsfVN2uI0WorfPxuWg8McXI1
            fQSZ+J7YKTPvKpk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:22:41Z"
    mac: ENC[AES256_GCM,data:5BBF7CK6GagYtuE+yMQN1esqaysqADQluXcSAQvWXxGjOfgP9WcmhI5h1geqye5+SiM+wdoE0BixViyGtZ70zhpAMD3jqUHzxCB1RpQDnqg1M32W+NqNTQcsj2Dx+AC36jiz1VREWBbIa9AvbRn39yYUhXTrMuBmB3SyIXdC/Sw=,iv:hKX7E1H6nS1+nJb21XQWcjhHIz3uru8Rrr2yA3SijNE=,tag:Xcx4+Mw4sHTTOuXKyqk12g==,type:str]
    version: 3.13.2
