apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jtADydojOInn0Fyj31mu41EwmFuI/qvicplZU4Tow3CZJQUYcpBetV1yhfL2YGX9xM844nbOvK/31/rARavz4RThWnvj+dh10Gejk1adSGT6e06HtUq49TBMd4UQf8Dy2uajnIU7vB+auXTzjRvktvE38f8tNwLZC1YnjGZHxvXgaZaLT3Mr8CPBJqJpySbI8VJLSEKq6hTPHTJczm9kkD8juw1S2Kx/9vx0O0OiL720a6uIZZHrH502gjvjJZ3uZwiMmQ2k8mMivbTZc4ng9gl8i4GF6JZfO6qQHbKn5NFgyjhIPQobA6vfznU=,iv:G1lXEjOH7D9ZBnq9Q424l3qIyWxD3UW09LdJ1bdH6aE=,tag:s62CTUMo9FunSHcpRGgyfg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISXVjVTE0UXlaczR1Njlq
            eCtIR1BnTzZwQ05KRHZEWnBnL1dHMnA4UDM0CncyY2xUb0NrZ0hVeld2V3dxS3o5
            Vy94TDdxamp4V3VrVkJGVWVCc3JPbFUKLS0tIHRvS3V0dXJhdjJlL2huMjRKSU5s
            TVBIOUl5ZXlaOSs3SzM5emNQY1FVSjAKa3Iy22dDHvoLWOWxQxYeZI5oNgkQ8X1L
            5Qt1fw7CpTseScuD+AwURqDbIkmd0fF6YQicgZ6d7RTD6Ac3JA+LQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T14:18:29Z"
    mac: ENC[AES256_GCM,data:Dll+FmLRzidGmbg5PsMSyrsOVzPEqUn+LGdMu1OEPB+BOOZ4/UrET1znB70pRoQ70L3V9qcKZH7uwQD7bMDxtUnYOZUzm7/nPiZYsOyiFuxvs2sKF/uLKSqSpwbzkntWFzQLT/i/5wGOPLKkAnTlDUBeRQhNJpm9UuHVkpj/zBM=,iv:8GsUKxqNAFGAanOVQYFcd6X6exEaPKJmbCaHHUg3yF0=,tag:IdDnuAV8TQsdyvnMRfGpvw==,type:str]
    version: 3.13.1
