# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: rustical-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustical-data-longhorn-pvc
spec:
  replicas: 1
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
