apiVersion: v1
data:
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:ACZPElMNInR/34HcRrAOw2xP5FkFj29VLwoUITXNnmtx3MLK6T95zeISEhIkMrdQ7JaN0yS8ObE=,iv:PoCNxCkSX4bWYZLKgWUK5vMP5Xfdyb5HuEpsJPjQPXM=,tag:2lz7WUM6oC7JCi173O0Blg==,type:str]
    COUCHDB_USER: ENC[AES256_GCM,data:KsjDi0MlIgn4t0DL,iv:SF/fjyR2RJCE6pMbxRbzTGRJht0Emx1akrVTYDk+moQ=,tag:NGUjQOlrJCt76s0eBwwX5g==,type:str]
kind: Secret
metadata:
    name: couchdb-credentails-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdmJ4MzFFODcyaXR3VVRu
            Wm94a1hwRnJ1TG9EdndzVGdQcnAxOXZPSXlRCi84V1d1Z0F3QXF3NHoxbVpiTHA0
            di9rUjgyZGk1MGhnRjVlR2tyU1YwRkEKLS0tIGZZU1orOHo1Rng5MW16YjhBWVVt
            eHVIbzVjcXdlVzhTOEQ1ZFZkaVBKWjAKbR6g+3rK/2ZRi2T5rDmkpUH0K/UbveRy
            6SQ3sZghELzRhQjMKbFYZXqXaaiShbrhrssSlrdJfUz+F5UXQjeQYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r5du8q96u964qrcrc9gemt3zj9mumdc390h4scqpwtkk6pz47d0s3ce7kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:23:10Z"
    mac: ENC[AES256_GCM,data:ECNta4UteH86OoYciCSFudv08n5YiyeUtNGPWGd3YekMCI5n+UOro8XiMLhPJfkKBxBrnqvaQwpfGaXNsGg2rXpuR1lcf9lkvVtjd5SNhdS7mRj2WBPsnG3PzWRXddTRWX8AecQ7t+ZHDfCR1FzIrEvKAHoA2VQEmAZ696mmnSA=,iv:gnJh+uc+dDZsecKDuvLodnD3+3G9Yb5unmkQbMtRYnA=,tag:xD+QLAf3qCelqnksmNhuYg==,type:str]
    version: 3.13.2
