apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6Oi26raoMvtACw2R7AHXnnGQ0TrjVW1+uPoMcOXYGJZgFzAmCmsG9vmgWNZfA34Y1LEgvE0bxprDewgaFiYowtnPvcrr4CUj//M1AoWhpP3EgJX2WTZKJtZQLcca73OrT3OF5+wBFJ5/3WPaBbUnftADzsdSkEleK/yaSDZGxy6CmvzrOLWanPcskT+mF5wvYX9GZRz/YssYG1zVz0uAS/Babq9CasbrvEg+kT9dn90QTw5yOl28yjfLtTHjsFvO4pT04IKqvYmQ32mIqzPWE4RUKlESeICHKkPFEs9aiIigFL67XWa18EypBhE=,iv:cfqVPbghsc969yHugBghUNjshPkin8lL33EJBG5u7Ro=,tag:qY78UGclUot7q5miiKkh7g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGNBek5Za0Fy
            U09jYzFTZTdVWXhONmwrODdvQzdlSFM2UzBJc2FPS0VlOWFxMk1raytOOTUvRFZD
            SEt1VFA0MHgzcW9oN0pBbmZjSndrZzJtdXZPY0hFL1pBdzhvZE5CV1FabmpGZUNF
            YktReGdxWGJIeExzQWxDc3lYRTNDWTk3OVE4UzBsUy9Lb2FQM3IzVWptYUlYS0x5
            eE9WUkZFdklCSmJ4OXZQRDcvektxRTJNS3FJS2xMdUEyVHVrMStHUnBnK0kyYUlU
            T3FiVGwrYlh1SFMyTE4xTkx0SERvc0E1UisxVkUvWVpoK3B3dmVwNGtxR1Q2TExy
            ME11ekxSWVhuNDBnaWhHUjlCbFd1Yi9oMnNIRWhWK1pzTStkL1F3TWczOWRMZzIw
            MUdBYmNmdjVGU2ZzNmRqSWRyYVp6V083QzY5TllORXZJVTh0OTFxUUxPbStHK1B6
            WE5uVytqU2FKaE8vNWpMSDJEbTJkaVJwRm9KRDMrT3Ryd2QrSWsvazlablBhU1Iv
            VWprY1M3Y0d4cW5VZWNqS3YrSWc1NkYzNGNXeE13L2FPYkVobmJGS1NCeE0vZGls
            YVZNcEhVMVBHMVJ3bU1kbW9wT1RtdDhPSWFBOEFsQVcvSGp0bHoweUNPV2Zyd3hW
            cTJRZTlXR3liSi9iZFgvcEFiVkduTUdFVHc2SWhoM1g0MVhrelVSSUUyR2paUnYz
            WDQveHhqNklnYjhKSlV5dXg2aUozN2NSM3RjVkVKOHpKZllTZk1MOGIxaVYzOGJH
            eGFjakhwRHhRZnlEaGYrQ2JKWlpJUXh0MTVXSEcyU1EzUWpGUHZ6MDhYSnBmdlJ0
            R1Y1Zm9hVFh6YUpVWmdIbWpieHVjYkpiZjE0b1NDdXFpdWZ0ZG1Ia1NWQmpHRzIy
            UjllSXV1SHFzUWxUN1k3NXg2Y3NQOXBsRjNkRHhlQ0pqam9jRHJrS05TR2JUd1h6
            TTF2eS8wRkJ6S0FORnp0a2ZzUUpLUG54c0NDMmo5ZU1KSHdhU2xQSVZSWE1ITHZq
            L3hRUHdOcmVXNWlxVDBzbTB4Q3l0Z3Q0MFR2aXJ3TzI0Z3JrVnVxVDdjMnRFWTJR
            c1R3ZmwxczBpbkhuRGV0YVliMnZYZjVFNHFDQ1pxQmxLbGQrK3YrN04rZ29iSVli
            ek1Ba200bm5ZY1ZSVGkweHNlSjVzdzBENUI3RE1Td3ZRM1dXNFRLY2FHdEJoOFhn
            ZjBLM2ZlVElaRHZGME9wZE0vUXRQWlBVUHN0ZnZVNnRNTThOUEE0N1FVdlIvazdI
            YXhDSTRoekhrVUltTXJDLzhka1lNNXVRWU5hSUpEdjNka3dMamVjMXpVUkxFWEVJ
            MGJmWkc0c08yR3E4VlVtSk1oR1ZIZm42VDFwQTFoSjhjZ09TcWprbWcwcmxDaXla
            UHN3ckxadC9XVGNWMGpKY09SYjZFN3RSOUx5cnhsQ0FTQXdzdzZUdldySTRtNDZ3
            TU5kUnFibjBlbWV1eXk3aGg4MFE4eld5U0ttZHZ3eVNua1JEUnpROElQdFRFaW82
            Nm9SRitZSFE5VnJvK2RRNzlVb0VIakFrbGllZTlJYjFXVlUrSmptUWljVnl2bkoy
            bEZBYlNOZGw4YzlrU3ZEMjFQamVWS1NobWliamR4dXl5MmJJcmpmazhpYUY2WmNG
            TDVqUCtuQVN0Y3daZmFlUDhyNkNrS0FiUGJNcUhpNFM2b0VPNkg1dld2aU5NZEQ3
            ODFmWkpCRnFYQS9KS1lKNGNUQ3ZPZ3lYeDBYckREbU1ONDNqcnY4TDZyZ3NyUWt2
            ZlJoY053ZnJsY0twUEJKRnp6YVZoT0lVOW1RRTVxa1dJVUtkSndySFMyY2FnRzkz
            R3dkNnk2bU1tZm5KdUtlWm0zb0l4cFBCeXN6ZCtYaC9pN2s2QzNDc1JkYktJVUxz
            WmFtUVV1cXUwaEVTWHRMWkdDOWI1RG41ckhkbEdmRFU1N1UrMlE2VnlXdkJYZwpo
            RkJXWGNvbW90M3g2a01sVTY5Ny9GUmFDRElyRkowanJnV09tQTFXVHRBCi0tLSAr
            ZHlqU2dRZzU1QUcvM3NyK1NDSExvSDhhSkY1NWVkaFBXS25VTkVpbDVZCgMbHUAA
            jHlbzTYuMSCo0H0LMwNnrF6NlO7kn3F+7xSRnEJB673DB34yljpNXX8edeAvBuJS
            SO4O0nHtU2KByYs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T15:49:06Z"
    mac: ENC[AES256_GCM,data:rfs6p9T1+CV/CtnooTB1Y8S9hf/3iFDQ7yM23j7lH1Bq54wB7mw2U4pZPYtpPrnUiaRxbqCxFc8FvWlZ24UDB/Vxkr7BnNZ0wZdMRaS1uKnM4dSU13OOe9iYqGyNE7shgqEbAUehXQhzMLis91GYJ/r/+9liJ463ub56sVSCaaY=,iv:GsTxP5Vqb5Bis3niCG6maAnZuNJOarhUNeV6EiuCpPg=,tag:rP0FN5sAkYDyeXrm76ufeQ==,type:str]
    version: 3.13.2
