apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VtFPdt4f1C05cXvz3Qi4TBl2hVxqh4lNcrEciaAstRfLQApBZJVEhD/yo1R6fnioNQwII0cdk6+oEwj17yJwa+a9UfezMGhQ7hA1llnzZuJ/LqOT/ALQDfJgwSmVwwg6eDipl9qaY0m1LUST0FaH7KbEeRvIMXoPhGMXEVmv6EgPKFU6kGyvILHlon1dzXs/guM7SoTVwMBQmGLq4r1DY1kDbQjdv3xKOyzCupdebeAtJkdnPm2nrNPQ4YX1eclDQGZLvfT8MQupFzzThrHw8k19Yg2kavJPqBMrOnYqXC3v2bkYh2v97KA7cC0yyddg,iv:yhoXowSVIDCHJASGqvb6C4rWvihcYsEI/E/rKU8Db74=,tag:x1AIAlzN33Ch+0pee7R77g==,type:str]
kind: Secret
metadata:
    name: ghcr-registry-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IENsWWNkclp6
            bHpueHk0bm14Q0paaTVPdklBRU51TjUvc2F0Y2FuaEZZbWJ0VGdEdWFsdmwwVlU2
            TzZEZnQ5MlpwejlvNVloUkpiaEZsRWptQzJScDBkd25IMjk4ZDRRMHU4UjR6UG9v
            RjdVN2ZpWmswc09XZ2lmSC9zR3VwVDVjY3N4ZFVWOUtsejU2VHFpby9tZkFhcERs
            bDNMZi9ZQzJ6dVZud1QwMFZGZzBvNkVOUFcxSXI5cjgvM3pJWkNMNDJoRzFIM2FH
            WjdkMFVweGZjZDNweEc1QTlsWXd1REZKdGtjc1hMY3JteGttSEVCV2dFalNrbUt0
            TnJ2MkF1Kzh4WEF6QVdmdmlZWmJtWDZjeUxvOXBVMjlINnZ6YTYydks1WkVhYVhJ
            SEZwMmNWNlUwYUNYaFlPSmZ2TW9uMWRjVE85UDBWbS8xUHJrVWt6bG9GWEN2RWNT
            bklaQlVtWWVyd0FXV1BBbWlMTENEU2ZUY0tEVXJISUV6REx0ZStJckIzWFgzc1kx
            M0diOXF1MEJ0QWJNRisvT05HWlhyQ2pJbUEyd2E1TFluSWRLWklBSTJwWngwNG9M
            bzF0K3ZWaUQrOHY2Q0pueHRFb2s4aklYRVdWNGNuMlBYWnVWbHBBdDlkcEpNbmZS
            dXNBRGI0NWVuZmkwUDhoL1A5NFNzQ0xUVTVia01wZ3phbkxzUjFGbTNuWVBRMGpX
            OWRFZkcybVFaeVd2YmNUb0Vkc21XYWJDNDAwV1EzcjZmR1lUYkRFS3lUWWQ5SVRC
            c3BvZVF3Y1hTSElRT293bXdpZHNqdEZsV2NTdStLamJVdlJrUmpLZFpSU2ViKzRO
            cy9YU0NvSUI2VWR4TG9aeGRWTFd2cnE5VWlINEQ1UW9VMjNFVURraVlJV0YvV3hp
            aDNrMXJUTEdNbkNVcmVmd3d1ZEI4WUtGUzQxS1kyb3loL085OEFLZ3A2OUdIeWlV
            V3lHVTR0eTZjUndkaTY3elkrWlVyN1BaM1JaaVlyOXdPUVB6TTVYeHpqL0ZNZGxG
            eDZiYmFOWHQ3d2ZPckNQcWdPSE1NYXBFeXpCcHI5bDhsOU9peFYvRWc1ZWljYmRu
            QzIrZE9FMU9tNEhDcXRHU0lxUU5qSW44cXNvSWM2WlQ0WTRTSnh3ckR1czNjYnZ2
            a1Q1N0ZySUVZZVpwRkErTTBFRktkeTAyU3lOMC9HL2hQWHVWVzJndWNiOEE3QWNW
            Q3k0bnRYWWoxSHlmK0tJTEpKZ0RWblFsWDk1UkRvcUI5M29CajM1Q3E2dnFjeVJq
            VUpLN3lnbFljV0YweEE1dVd1QmlXTlNQSjExbGp2UVZxcVcvaDV1S3ptSThDcTl5
            ZGVYTjRyRFMrekhBa3kvQXNMZ3cwdFRweW4xU0RvV0lZWG9MYkVMa3V3cFRNTzYz
            WXZQelR3WWNCZGExR3IyaTF0eHlQRXRpcnNsRlhxVTgwK0wweHhZV2dPbFlFSmtp
            YVgyYndKMXZJU2IrOVFHaVVidFZUMldwa1lPb3g2czNrUUdRZ0VuTW9oTis4bmxE
            Q0VwSEJCTVdoM1dpSnVUNGhBazZ0dnplQjdnd0N3SDN0V09xMFU5NWo3WmErOWNw
            cVhOZXBmdGlIQzJ0akdiVHV2V25yaEpsdnNUZXpxRDVOdXF2aXIzYTMxU0U0QWtw
            Nm0zMU5pNGN3NXhlTEs2TGltMEZkMXJyMHd1TW5wajkxdFl3MHVBc1hTSzRhQU8z
            bUFNZ2cyZmo5bTk2d3lFV0lzQWE1ZGFsQTdnM0F3b1lCTkNGSnVGVmFQUEt1bnJ2
            bjY3WEZEVzZKNEVvdTUraVRIZzFwRXdHVXA2M1k5WW5NZTh1bWRlN3ZkWU9qY0J6
            UW5IYWVZY2lTZTk4SjFQSlg4Qmp0THZJNDNvM2xCa3ltNTJIZUNzTFRXemFDN3Z5
            L3Z6cXhrcHBXUlNPeTJmN0M1Zi9KSC9HMkFtR0ttMGUwbTU2SmZTTk15L0ZLQQpT
            VU9HeENpU0RDV2syOHBHcmZ4aEN6RzdzLzRkVHdMZlhQcWpWSkJ2WlpJCi0tLSAr
            a2M2ZnlQOWJBSFZDcVFUTmk3TWlORlN6a3hoeXltMndEdGUzU1JvQWNBCmgYjgVk
            krLb2AUlZf2Jbkr7UO9uQ6TTB58EGC3AnbQgP5v0wxPtbhX/o3TRrH6+WaH4VcUg
            qrF8ida5BtkEsbc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T15:09:56Z"
    mac: ENC[AES256_GCM,data:MIqA0KA3KGDKQMbctkbMn8bycmzCKKAo9KDYmWnyfEbDj5qE78AMKQneWGTeqCf0WzXcMJtgijyfg4zGFdrKqTHnvlsvA0TEMmPmWtqmx9UKQehgCG/Hwmabx8MlRJaM4jrGucSa/SEnhF0tU1Y5PpaMu0ePQSq7MEeZZ0u1cTM=,iv:kEoRPgZKEEMLUtucis6JxtiCeIFri8swK1wGNPYM6tM=,tag:qVI7yvjN54jIx9L7W2SgQw==,type:str]
    version: 3.13.2
