apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-sync-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

