apiVersion: v1
data:
  backup: |
    #!/bin/sh

    /usr/local/bin/forgejo \
      dump --config /etc/forgejo/app.ini \
      --custom-path /var/lib/forgejo/custom \
      --file - \
      --type tar.zst
kind: ConfigMap
metadata:
  name: script-map
