apiVersion: v1
kind: Service
metadata:
  name: forgejo
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 3000
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: 2222
  selector:
    app: forgejo
  type: ClusterIP
