apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-valkey
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: v3.0.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: machine-learning
    app.kubernetes.io/version: v3.0.0
  namespace: immich
