apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:YFoC0eiiglN0TDiK2fpjVGmRcUQCK2/ydAzcAXkDG9bPcEtWSBRI+5opdGzBI8F6qp6gtpkzTVg=,iv:AO2rlhbbvx1FkuSJqMokE+p2Yuad9/O+lbHIGNIw21A=,tag:EzdQ83e/JpUCU1rExnVHjA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFo3NUhRY0Fy
            S3JZSXp1bEMrVDNSWVJmUlJvN3NPTWMwbkYycEpmaThIc2FDQmRIN2pwaGd5N243
            TXAyVWRVaWMxNzk3M1FLdEdTanhGVkF0N2pqanU0R2JCTHpMWnBRTXFGQlQrUDIx
            bDN0Y1JMMFA4QmlTODh6bHRQQkVXcE5reUF2L2VXWTVsa25vbFhET2t1TlIxRmgz
            Y04vVVpQdTBIbFh5akhyMkRRSzFveWRwSjA1bnVSUGJsZVFHQmZDbzhFR0ExR0Vm
            S0NvSHRLTkw2cTZUNDRjSFZvMGlyWjdIM2RDaGZHcFNoYmVBcnZDZTFmTkhKTldx
            RGlTcmNTWXVmdThRaU92bk5odWVVSVRlcHc2UXRJUXBIenRMK29VTE9mdk5LVWxX
            MVhhVFo4WnlHNktOeEgxaEYrZVBhakd5dzJqVkNXTDNBcDVOOXlyZXVvbXB6ZVV5
            ek1rd0hrd1dBMlM0NGtaamphaFQzWHArQ1BTZ0MzNHFzWldrd3FjY3MwbFhSZktv
            TS9XY083cU1ENHFBUlhDdFkyWWcvSXdSMlRPQjZiUENuZkFRSEk3OTBWYjhLeXNI
            TnlHMlM3VjJOWlpZUVdOclJjQWlzNGxTVkYyd2ovazB3clZsTDVQTkp1YURQd3Nq
            eVhFdWw4bTB2cEZaNUEyV2RwYS8wV3FEY0JidS9lUVRianMwOGs5WUtoTjE5WThj
            Y0ZrME1XaGY0SXFkeE5Cb25NNUdHOUllRENJWGNqMjlaYWJBcHhwbzFmaE5ZN2Ex
            S0dhT3h0NUp2bWNESHdadXdtUDVvdkNaL3NTZFZPS2wxbFBDQ01jZ3BnVnMwRnpN
            RUhRZGRNU0lZRkZ5M01kRk83N2k1T3k3a0ZJY0Q0Qm5uanhLMkxPMTBXaE15Rmtv
            d2JuNDlOWWJlTmZhTlR3aFFUVURCMnRtc0ZHODZzTGYvZDVJOFZxdm13Mmp4Ulgw
            dEFCMXFTMnk2UTJhY2N5b1MxWFl0M1pyWXB5cmY2OVJ0OERUSlRsL0xHemx5Y2xH
            cldhY1dhSjRqNjNyNm95TFlmbkYzcEs4SVd3ciswQmFPQVNTbFFxYmIvbzhMcWE2
            UDFmZm1MQXdnakR2eWFYcFFhR253WmpReDdTcGNPM2ZsclB5cDZMWStXQWhiNU5n
            emhHTFhqVXRBRFJpKzVXb0p4Yy9NOWxvbEtBQ3N4N25VVmxvWUpJVHJOV3RFMGZV
            cy8vY2ZPNEhpNEFodTRSZHUyd2ZJY0hzUWh0RmEwYmV1UDlWb01QS25tK1l1amZn
            SFlJcnpmdlhVRnF4QU1EUzhnU0NQcGc2Y1pWWXdsL1JUM1dlNWJiVG9pWDJ6ay90
            REpLRXJSRi81Z3JRMnQweEtDTDJ6TFczem5pS1hqY3VkNUFyY0d1SFFuTU9WYUZT
            b0dJajhoTGkxUlU3TE15M3YwSDhndzdoZVF6VFpJaEJYMjVwZ2xYdXZRYWJ4NlI1
            UUVnOVVyRGJHWG53RGFIOXAzUFB4M25ybWo3cU4rdlZHbjZJZ1lVZnBUZWpDRmlp
            KzFaeHhDZUZYc0xsS2htekZkMWNxdU00MUtQQUlJZnU0d09Ta0tJNlR4cTNhNFdL
            VlZqRHRUQmhYR1JFZGtrdjlrWmQ3Nm42UExXOVRVUWxYSUxlcGhYNFpWZ0dyS3lS
            T1NabEJ0VFpxNDhCMnF0UnlLT09pLzIxK3NnUGNXdm9tSWg2KzhrS0o5VnptTXp6
            WUVzb2svY3p2VmpBMUtLNGtzb1pFTTJ4VG1CNFlMd0hXcyt6UDRuMnlrQ1kveVZB
            UlBvYTVDVjdQbXBpc3hsekVBeFpxNXZpZVhGajMrR0hqcGI0VUtMdy9GUzQyZEZZ
            U240aDdSK0pyQzJLYWl3ZHNyVXlBd0d6QVg5aGRTSG12Ykhuc1Y1ZzJNNTR5bG5N
            WVBLU0ZJT0s1ZXZLYTdBZ3pBRU56dWZ5dU5jaU5HY2k0UUU0QndDaktiQzBJQQpl
            clJiU2xMcTNWNEJocS91TGVLak1IQUhvd245b3ZPMVA3ckorejJacldjCi0tLSB5
            ZjRtbE1aU0E3U0dscFl0UGh4KzN4dHZsaDF1Yng1cmk1KzlSWjMzMzk4CujYaIr2
            jMVU6hR7i2CuSg5sakBD5L/q7GVoCSiNWdxnSxS0fioufHXET/mEbsK0KSWZTJ4S
            93TxTf8uzGBoHic=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1hqdcmz6u572czfme5ua2wqq05zgc9zxz245zc2t3zvgfcyye7t2q3t5uhvaeqckjsgcjmfanv5g2dvc53ndpgmzum9mdkjunjgygf9p39eyzrp6lyceywmzgr8vt6h7e9q2ztjgl0yjmcxthe54gnaft96yapwkyzzhlyu9ftepxn4phw45xvz0ght9ryzv26jesx0my58uycpj6wse0e94qncj3zpjhfueyrdk3skr5y3wfukrmxpjcns2nxtumndg8qxggjn4nvjhq5v8rf9klcced6tyzg97vup8srhsfg92kz7y9reccvnp6a4mxhxly8z93kudq9ua9ft3vnw4r86jng4f5n30k2wgljhqcc28rwpw2ztdg9q4ck2j62agek94r575f52mhxxc8cwg0yyakqqgkfum6gp3tlwh69ss6wuv88yns5g5qfnnuz30w6p3a0jugk6r4se7wp9n0ukk6teutspdsl32zk6jkpfm0m3xxmyc49nkyafzeyrc0vrnjnnx7y37w4qgmyrye40glc9w74g5t836s3fzffmdupj9yx90vuxu3fs5kkgq87xy4gtspkr8gapmxhsnaw5v3xmm82xh3vl6ctq8km5vcjwju72c4r7g2hxamaqrgu45q0nm5dec5hq8hxp4mewq2hgqtdm4ntwazfz2lf938qah2jddujsnpkpnzycwz5vlvlqxllujgefv5c7fjnwcmnfsh6kuypwgmtrzeq0jms4pqzy4gglplwzr8ezy6pxpe4rva9zdcjqg48jshnlzt9z2697pcw0ej3nrrm0yqt8qns6x8gjsukz94tdtnwq5wnlrmwvrrk0zyjhhlc463k5tnwhuqa37hj806csncfjkam6tgzfruej5rshlkdxpn03ye4d5k5ytnm2rxxurm3rrfeyykmp27zt4rq0a6f5z490z42z0m9xtm98c4ppszxm85ykhnl0z82j26nkvfv77en0pmg9jt6vuqv9slq6celd9e8qjdspvluxvnndx8dvm57r6vjg979ty3cdzh8367jsjps2rqwyweg90unxjfj3z6xwutgmeu9dx9txkrffyd9z5ue5qhhvu4xs898wkf8gx8tqf3c69srplmsfsevpf3xe7kzgxqjjd9tdp8qdqywlt7wn9uav3rwrj44xhtrdpxh9syz5xs47w0rjturx84kdvry60nqqex02spm7e5ydwks9dds3a4hyavu8q8s02hktj540z50qp0pqyvqsemyg9un62kgmpgk8vccj9r7cylrymez9qry4uy5pvfysq88d3s8uxgttkhx97nhqf5dywwaamr9yck66kgfj4yrzm37s78q2dd4krgw2je8avuppsdmg0a4gnu47q2773k42nhfdd0v5q6hcq92nqftyzxd4yhn93jxkxwxwwfdefcsn5r0zam8ytmhxytyjj3v4auxjvsf0m85esnxkte3tycfjvf2rzev5j22nefgyapvxpprmas5tz3qjhuw9qkrwmru9c2d4rr62vpqcrvrswngq038ur5empr96aptu52p0cq9psuyxcqqsch9qxesyd5r2m0vgml7p5y6yccp5scpen2ep04ljarwq2xs8aysngc0qxw4t3ckpqu9x3xt8xp9ayz3hkzzj0x7xehlr9y9hdf0vk6k3f342778dh7wamujez9qy33pvezj2w3c3crhp9e5xntaxupsatyfr2pz4kl6p9jjmmyf5nmhu3svj4qwx588vmyv6m2heqhkrkgktk8ppc8fg5yaqgt8tzm0exetg82g4k8qjvc4npxyp24fhm8jeptseje2m4yyl7jy4lxql98ntcf3mq22qejwddkck3eapx9uc5wpmpzvcqx3xzv4fcwpd5cqytzkwtg0xfzltpcty27pcwn24d5q93sfeh4yqmawlkf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:23:31Z"
    mac: ENC[AES256_GCM,data:j59z2GEii2nPvDRbk3K+KBx74ZUjkP4CrVrfzB0YwWJsGMRzzq7d4PwoC/XSs2MnnRTUXGwgg1SpJdBfhZ384yo9nWaGgw2KmY3y5eLAZd44gmtxymsDR+xTV9p27zGYhMaxbnE4rmrdy5RnkKT/15l/FJc0bDlxC6P9SutYQ/Y=,iv:DlLrvzwgk6OCuUsV0o3QXpOwMzstdc2OM9+tEqAn+jI=,tag:kQKVVsanagyRa9JZHp8HxQ==,type:str]
    version: 3.13.2
